### ISSUE TITLE
global color_bad

### ISSUE THREAD

**Issue by x421** [vivien/i3blocks#100]
Hi, is there a color_bad (or something else to change the red text on my eth when it is down?) :-) 

Could not finde something about it.

**Comment by msx** [comment]
+1 for this feature, this could be really useful.

**Comment by oppenlander** [comment]
+1 I made something like this in #90, which let you set a custom color when you exit with `urgent`, but i3bar almost immediately updated to break it.

**Comment by acrisci** [comment]
I would like to see this in the i3 config with the rest of the bar colors.

**Comment by Nycroth** [comment]
Feel free to modify the included script. Just change line 38:
```bash
echo \#FF0000 # color
```
The included scripts give a great starting point but i3blocks has always been primarily to provide a simple framework for writing custom scripts or modifying examples to fit your needs. If you haven't done so, consider copying the scripts to something like ~/bin/i3blocks/ so you can modify them as desired.

A custom down colour would better meet people's needs but would require adding a flag or option to the script; something that is trying to be avoided.

**Comment by x421** [comment]
Thank you very much!

**Comment by Airblader** [comment]
Note that this obviously also changes the way urgent workspace buttons look. 

The name `urgent_workspace` isn't entirely correct anymore due to this, but introducing a separate directive for it would have been overkill. And anything else isn't compatible with previous versions.

**Comment by vivien** [comment]
I'm closing this issue since such an option would diverge too much from the i3bar protocol. Thanks for your input on the issue guys!
