### ISSUE TITLE
Nested functions break compilation with Clang

### ISSUE THREAD

**Issue by f-koehler** [vivien/i3blocks#102]
Hi,
I just wanted to inform you that i3blocks does not compile using clang 3.6.0 (GCC 4.9.2 works just fine). The problem is the usage of nested functions. Do you really think that they are necessary?
If you think so I will keep switching back to GCC for i3blocks everytime.

**Comment by jpleau** [comment]
I think i3blocks should build with clang. Some operating systems (notably FreeBSD 10) use clang as its default compiler, and gcc is not installed by default.

**Comment by f-koehler** [comment]
It works if you move all nested functions out of their parent functions. Clang does not support nested functions (not even in 3.7: http://clang.llvm.org/docs/UsersManual.html#gcc-extensions-not-implemented-yet ). I cannot compile the code as-is using Clang 3.6.

**Comment by jpleau** [comment]
Yes I was not saying that it compiles with clang as of today, but that we should make sure it does :)

If you can send a PR I'm sure @vivien will take a look!

**Comment by f-koehler** [comment]
I'll do that later :)
