### ISSUE TITLE
Short text displayed with plenty of screen left

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#104]
Currently I have three monitors, 1920x1080, 2560x1440, 2560x1440 with bars on all of them. The short text for my blocklets is getting displayed with the 1920 width screen only 80% full.

**Comment by vivien** [comment]
Do you have a screenshot so I can make sure what you mean? It sounds like an i3bar issue to me, not sure yet.

**Comment by kb100** [comment]
I was wrong, the 1920x1080 screen was only at 80% full because the short text was being displayed. The full text would have overflown. However, In the process I discovered https://github.com/vivien/i3blocks/issues/104.
