### ISSUE TITLE
Short text/ long text inconsistency and lagging updates

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#105]
My monitors:
1920x1080, 2560x1440, 2560x1440

Case: 1920x1080 monitor full text overflow
Result:
1920x1080: short text (expected)
2560x1440: short text (not expected)
2560x1440: long text, but shows short text immediately after switching workspaces until the first update occurs. (not expected)

Expected results:
short, long, long (preferred), OR
short, short, short

**Comment by kb100** [comment]
On the screen that flip flops, here is what they look like.
![screenshot from 2015-05-09 08 57 59](https://cloud.githubusercontent.com/assets/1966710/7550488/5441d10a-f62a-11e4-8efc-4eb25df0bd40.png)
![screenshot from 2015-05-09 08 58 02](https://cloud.githubusercontent.com/assets/1966710/7550489/54425f76-f62a-11e4-8af0-a4676b7d9815.png)

**Comment by vivien** [comment]
Hi @kb100,

Again, this seems to be an i3bar issue to me, since i3blocks only outputs the data (`short_text`, `full_text`) and let i3bar decides what to display.

Maybe @Airblader or @acrisci has a clue about this?

**Comment by Airblader** [comment]
I think there was a pr to fix this on the current next branch.

**Comment by Airblader** [comment]
https://github.com/i3/i3/pull/1657

Maybe try running it with an i3bar that contains the above fix and see if the issue persists.

**Comment by kb100** [comment]
Confirmed that this is an i3bar issue, not an i3blocks issue.
