### ISSUE TITLE
i3lock on click not working

### ISSUE THREAD

**Issue by parkerlreed** [vivien/i3blocks#107]
When I click it locks fine but then doesn't accept any keyboard input making it impossible to actually unlock the computer. I even tried adding -n to keep it from forking to no avail.

Arch with i3blocks-git

**Comment by msx** [comment]
Hello @parkerlreed,

What code are you using to invoke i3lock from i3blocks?

**Comment by parkerlreed** [comment]
The little snippet from the wiki 

https://github.com/vivien/i3blocks/wiki/Blocklets#i3lock-on-click

**Comment by kb100** [comment]
@parkerlreed Are you sure it doesn't accept input? The -u flag makes it give you no feedback when you hit keys. It's possible that it is accepting your input and you just didn't realize it because without this flag it gives you some visual feedback.

**Comment by parkerlreed** [comment]
Fairly certain it just wasn't accepting input. I used the same i3lock command by itself and it worked. Thinking back it might have been some weirdness with the pam module I was using for authentication. I had my fingerprint reader setup as the first option to try before password. It worked in i3lock by itself but was kinda janky on showing actual input. I can try my setup again but it'll be a little later in the day. Thanks for the reply.

**Comment by parkerlreed** [comment]
Closing this for now as I cannot get my fingerprint reader working again. It was a complicated setup that required compiling a very old libfprint. Might revisit later if I get it working. Thanks.

**Comment by mekhami** [comment]
I'm having this same issue. If I click i3blocks to lock my computer using i3lock, i can't type my password once it does lock.

**Comment by parkerlreed** [comment]
@mekhami Ahh thanks for the update. I'll reopen.

**Comment by kb100** [comment]
@mekhami @parkerlreed and anyone else having this issue, could you post the portion of your config that concerns the i3lock blocklet?

**Comment by parkerlreed** [comment]
It's been forever for me and that wiki page no longer exists. @mekhami Still have yours?

**Comment by mekhami** [comment]
https://gist.github.com/mekhami/f5cf9700740d14ee717d Here's my i3blocks.conf

https://gist.github.com/mekhami/ca22c91ccd46282fc737 Here's my i3/config

**Comment by kb100** [comment]
@mekhami, does using 

    command = i3-msg exec i3lock

fix your problem?

**Comment by kb100** [comment]
When writing your config, keep in mind that whatever command you put in `command=` should terminate as soon as possible (exception: blocks that use `interval=persist`,) precisely because conditions like this one can occur. If you have a block that spawns a program that is not meant to terminate quickly, e.g. any GUI program, then you should use `i3-msg exec` to spawn the program.

**Comment by mekhami** [comment]
okay that fixes the problem, although it changes the lock 'button' full_text to `[{"success":true}]`

**Comment by kb100** [comment]
full_text=Lock
    command = i3-msg -q exec i3lock; echo Lock


?

**Comment by mekhami** [comment]
works like a charm. thanks for your help!

**Comment by vivien** [comment]
I'm really sorry for the delay guys...

Thanks @kb100, `-q` is the way to go. The following blocklet works as expected:

```` ini
[lock]
full_text=Lock
command=i3-msg -q exec i3lock
````

Closing the issue.

**Comment by lckrspirit** [comment]
Please tell me. How i can use command on my script? 
`i3-msg -q i3lock -i /tmp/screenshotblur.png`
Opеtion `-i` not working. (

**Comment by lckrspirit** [comment]
I am resolve problem. 
`command=i3-msg -q exec "i3lock -i /tmp/screenshotblur.png"`
thanks..
