### ISSUE TITLE
Potential problems with char buffers and their sizes

### ISSUE THREAD

**Issue by or** [vivien/i3blocks#110]
``` c
char *lines = buf;
linecpy(&lines, props->full_text, sizeof(props->full_text) - 1);
linecpy(&lines, props->short_text, sizeof(props->short_text) - 1);
linecpy(&lines, props->color, sizeof(props->color) - 1);
```

Implicitly relies on `sizeof(props->full_text) < sizeof(buf)`. The former is defined to be 1024, the latter 2048.
This currently works, but it's possible that this causes problems in the future, when one of the two is changed for whatever reason without keeping this in mind.

Similarly

``` c
nr = io_readline(block->out, buf, sizeof(buf));
```

Might fill the entire buffer of 2048 chars, not leaving room for a terminating `\0`. Again I don't think this can break anything currently, but it might be something that introduces problems in the future.

Last but not least the properties struct never experiences an aggregate initialization, does it? I'm not entirely sure on this, but isn't there a chance that the char buffer members aren't initialized with 0s? I know C guarantees it the moment something like = {...} is done, but without it it might not.
And if this is the case, then the `sizeof(props->full_text) - 1` as a max for `linecpy()` would not guarantee that the last char is a `\0` and `strlen()` is called on that buffer.

I'm planning to attempt a little refactoring here sometime soon and would send a pull request, just wanted to point it out first, in case I'm on the wrong track.

**Comment by vivien** [comment]
i3blocks master now support properties of any length!
