### ISSUE TITLE
ERROR parse_property:98: unkown key: "markup"

### ISSUE THREAD

**Issue by PrimeMortal** [vivien/i3blocks#113]
I am using the default i3blocks.conf and it displays this error. I removed the markup but then it just displayed the date and time.

**Comment by Nycroth** [comment]
What version are you using? This error reads like your version doesn't support the markup tag. I don't think the pango/json markup has been released as a stable version yet.

**Comment by vivien** [comment]
Indeed, there is no release yet. @PrimeMortal can you give the dev version a try? Otherwise I'll try to release a new version asap.

**Comment by PrimeMortal** [comment]
Where can I get the dev version? Is this also the reason why it exits unexpectedly as stated in my i3bar?

**Comment by Nycroth** [comment]
The dev version is available through the git repo's master branch. If you use Arch, I know there is an i3blocks-git package in the AUR. If not, your package manager may have similar or you may clone the git repo and install it directly or with your system's BSD ports equivalent.

**Comment by k0377** [comment]
I can confirm this error, just got the same. :crying_cat_face:

**Comment by k0377** [comment]
fro #69: Replaced 'command' with 'command=/usr/libexec/i3blocks/$BLOCK_NAME' in my `blocks.conf'. seems to work

**Comment by mseri** [comment]
Thanks! I had the same issue installing with a non-standard prefix and your suggestion worked!

**Comment by vivien** [comment]
This was fixed for a while and now any key is supported as well.
