### ISSUE TITLE
$BLOCK_BUTTON for hover

### ISSUE THREAD

**Issue by rhetr** [vivien/i3blocks#114]
i want to pop up a dzen window whenever I hover over an i3block, is that possible with $BLOCK_BUTTON?

**Comment by Zopieux** [comment]
AFAIK there is no hover event in i3bar. You can listen for clicks though.

**Comment by vivien** [comment]
@Zopieux is correct. You can listen to left, right, middle clicks and wheel up, down events though.

**Comment by Radivarig** [comment]
How come tray icons have a tooltip?
