### ISSUE TITLE
Colored output

### ISSUE THREAD

**Issue by vandr0iy** [vivien/i3blocks#115]
Hi, vivien,
Good job with this bar; it makes me suffer the absence of a graphical alternative for the i3status much less.
Here's my issue: I tried to make the output more... colourful. By piping in the bar a bunch of text with colours as I'd do in shell. Like this:
printf "$EINS \033[1;30m\033[43m`date '+%Y-%m-%d %H:%M'`"
It wasn't a good idea. i3blocks crashed, and scattered all of the icons in the systray all over the desktop, in various windows...
Probably it's an expected behaviour, but, just wanted to let you know. 
P.S.: What I wanted to do was similar to that powershell thing, with every block having different bg colour. Could you kindly implement such a thing, if it's not too hard to you?

Thank you in advance for attention.

**Comment by Zopieux** [comment]
You can use the new [Pango markup](http://i3wm.org/docs/i3bar-protocol.html#_blocks_in_detail).

**Comment by vivien** [comment]
Hi @vandr0iy!

@Zopieux is right again. The i3bar protocol (that i3blocks tends to respect) supports plain text coloring (via the `color` property) or recently supports Pango, e.g.:

```` ini
# note: i3 must be configured with a Pango compatible font, like:
# font pango:Fira Mono, Icons 10
[test]
full_text=<span background="blue" size="x-large">Blue text</span> is <i>cool</i>!
markup=pango
````

I'm closing the issue, since Pango supports background coloring as requested.
