### ISSUE TITLE
create an option to configure internal unicode chars

### ISSUE THREAD

**Issue by aleprovencio** [vivien/i3blocks#119]
Hello,
I like the decision to take off unicode chars from the scripts themselves and leave the users the "label" option on i3blocks.conf to put whatever they want. However, I miss the unicode symbols for charging and discharging from the old battery script, and I guess that currently I'm not able to change that from i3blocks.conf.

What do you think of this possibility?

**Comment by Nycroth** [comment]
This isn't as hard as it may seem.

Lines 40-44: /i3blacks/battery
```perl
if ($status eq 'Discharging') {
	$full_text .= ' DIS';
} elsif ($status eq 'Charging') {
	$full_text .= ' CHR';
}
```

If you just replace DIS and CHR with your preferred symbol, you can return the unicode. If you haven't already, I would suggest copying all the scripts you use into a folder like `~/bin/i3blocks/` so you can edit any as you see fit.

**Comment by aleprovencio** [comment]
Yeah I know I can do that and yes you're right it is not that hard.

My suggestion however is about trying to concentrate all configs on i3blocks.conf so I wouldn't even need to have another file added to the setup.

I don't really know whether it is viable adding this since a lot of scripts would not use it but it's cool to hear what you guys think about it.

**Comment by kb100** [comment]
@aleprovencio You may be interested in my battery script: https://github.com/kb100/i3blocks-battery

![](https://raw.githubusercontent.com/kb100/i3blocks-battery/master/images/1.png)

**Comment by aleprovencio** [comment]
@kb100 very cool indeed!

**Comment by vivien** [comment]
With the new split of user contributed scripts in another repository, I plan to remove unicode chars from the default core scripts. Funky symbols will be welcome in the contributed config/blocklets!

**Comment by aleprovencio** [comment]
Yeah I guess this should be the natural path, you can close this if you want, thanks for your time
