### ISSUE TITLE
[1.3] ERROR block_reap:239: [volume] bad exit code 126

### ISSUE THREAD

**Issue by dmarcoux** [vivien/i3blocks#121]
Hello!

I have the error ```ERROR block_reap:239: [volume] bad exit code 126``` when trying to run custom scripts in ```1.3```. I did ```i3blocks -c ~/.config/i3blocks/config``` to test my config and this is how I got the error message.

My files and folders are organized like this:

    Config: ~/.config/i3blocks/config
    Blocks: ~/.config/i3blocks/blocks/ (volume and battery, one file each with the same name)

The files:

    config: http://pastebin.com/xTWF20G1
    lala script is just echo "lala" and exit status
    volume script: http://pastebin.com/7VURjf1d
    battery script: http://pastebin.com/cYntmmvZ

**Comment by dmarcoux** [comment]
Will this be fixed in 1.4?

I am on Arch Linux and if it is the case, I will just wait for it to be pushed to the AUR.

**Comment by Nycroth** [comment]
First off, I really like your idea for using `.config/i3blocks/blocks/`! :+1: I'm going to pass this along to the devs for version 1.5. It may help us with something.

Anyways, an exit code of 126 is a POSIX shell exit for "Command Not Found." I've checked, and your command setup is fine. Using `$BLOCK_NAME` in a global parameter works just fine. What I need you to check is if your volume script runs correctly. Does it have execution privileges? Do you have `pulseaudio-ctl` installed? Does running it from the command line report the output you desire.

It seems your volume script also does not use the `$BLOCK_INSTANCE` variable. You can safely remove the `instance=Master` from your config.

Hope that helps.

**Comment by dmarcoux** [comment]
Hello Nycroth,

Thank you for your comment! I am happy that you liked my idea for `.config/i3blocks/blocks/`. I find it clean and clear. Anyway, let's get to the real stuff :smile:

So to answer your questions, I do have `pulseaudio-ctl` and I did test my script to be

**Comment by Nycroth** [comment]
No problem in either case. I've made the same mistake closing. lol
