### ISSUE TITLE
Extend i3bar on multiple displays rather than mirror

### ISSUE THREAD

**Issue by Nixpower** [vivien/i3blocks#122]
Hello, I was just wondering if it is possible to extend your i3blocks across multiple displays, instead of mirroring them. Is this possible or does the i3bar protocol not allow/support this?

**Comment by kb100** [comment]
See the section on configuring i3bar. http://i3wm.org/docs/userguide.html#_configuring_i3bar
In particular you can run multiple i3bars that each have their own status line, and you can specify which monitors they appear on and where. You will need a separate i3blocks.conf config file for each separate status line of course.

**Comment by Zopieux** [comment]
I would rather give this link: http://i3wm.org/docs/userguide.html#_output_s

Relevant snippet:
```nginx
bar {
    output HDMI1
    status_command i3status
}

bar {
    output LVDS1
    status_command i3status --config ~/.i3status-small.conf
    colors {
        background #000000
        statusline #ffffff
    }
}
```

**Comment by Nixpower** [comment]
Awesome. Thank you for the resources!
