### ISSUE TITLE
openvpn state always down

### ISSUE THREAD

**Issue by boolean-is-null** [vivien/i3blocks#132]
I seem to have problems with the openvpn blocklet. I'm not sure if it's ok to ask here, but I haven't seen a single issue pn i3blocks-contrib page.
Now I'm really not sure whether this is an issue of the blocklet or an issue with how I use it or openvpn.

I'm aware of the `#usage` comment block.. the config file is named after my servers hostname (`brimstone.conf`), in which the following options are defined:

    dev tun0
    writepid /run/openvpn/brimstone.pid

But when I run `openvpn /etc/openvpn/brimstone.conf`, the state is always down, even if I run the script manually.

**Comment by vivien** [comment]
I moved this issue to contrib https://github.com/vivien/i3blocks-contrib/issues/5 where blocklet maintainers will be likely to be more reactive on this.
