### ISSUE TITLE
[Solved] Bandwidth coloring issue

### ISSUE THREAD

**Issue by boolean-is-null** [vivien/i3blocks#135]
Hey.
I have separated the bandwidth script into two up and download in order to color them separately.
Now the only thing I adjusted is the hex code at the end for the color and the label.

    # incoming
    echo -n " "
    rx_kib=$(( $rx_rate >> 10 ))
    if [[ "$rx_rate" -gt 1048576 ]]; then
      printf '%s MB/s' "`echo "scale=1; $rx_kib / 1024" | bc`"
    else
      echo "${rx_kib} KB/s"
    fi
    
    echo ""
    echo "#00C176"

Now I'm sure this isn't a problem of the script itself but of my modification, but I can't get to work it properly.

Whenever the bandwidth is >1024KB logically it prints 1MB. The problem here is that the coloring is lost. Values starting from 1MB are white again, how could this be fixed?

**Comment by kb100** [comment]
Make sure to end your printf with a newline.

**Comment by boolean-is-null** [comment]
perfect. thanks!

**Comment by kb100** [comment]
@boolean-is-null, you are welcome -- if you think your issue has been solved, please close it with the button at the bottom.
