### ISSUE TITLE
Color key has no effect.

### ISSUE THREAD

**Issue by beanaroo** [vivien/i3blocks#146]
I have tested this using the default configuration provided. Colors passed by blocklets scripts work as expected.
This occurs on the git based package for Arch Linux. Release 1.4 works as expected.
I am using i3gaps by Airblader, if that's relevant.

**Comment by kb100** [comment]
Related? https://github.com/vivien/i3blocks/issues/138

**Comment by SageEx** [comment]
In arch aur, i3-blocks-git has same problem. The normal i3-blocks is fine.

**Comment by kb100** [comment]
@SageEx would it be possible to git-bisect until you find the first commit in which the bug occurs?

**Comment by zenhaeus** [comment]
Same problem here... i3 on Ubuntu 14.04. None of my blocklets are colored, unless the color is passed by the blocklet script.

**Comment by Nycroth** [comment]
Here's the key question: is anyone experiencing this without using i3gaps? I had a play with the gaps fork but the project seems too under documented for my tastes.

It's just that i3blocks is designed to adhere to the official i3bar protocol API. If the fork has broken or changed something, there is *probably* nothing we can do. I don't use gaps so I'm not really prepared to hunt down the source of this bug. If someone (anyone) has this problem in the official i3 implementation, I'm more than happy to address this issue.

**Comment by japareaggae** [comment]
@Nycroth @kb100 I'm using stock i3 and I have this issue. I bisected it and the bug appears on commit 701dd3f704509278183090f9b3e66c546d5e0d68.

**Comment by zenhaeus** [comment]
@Nycroth  I don't use i3gaps.

**Comment by Nycroth** [comment]
Not a problem then, I will see what's up. I have a paper to write today so I may not get to it now but I will look into this over the weekend.

**Comment by alexbooker** [comment]
In my experience, this problem only occurs with [**i3blocks gaps**](https://aur.archlinux.org/packages/i3blocks-gaps-git/).

I think this because running:

```bash
yaourt -R i3blocks-gaps-git
yaourt i3blocks
```

Makes colours work :open_mouth:

**Comment by Nycroth** [comment]
Holy.... Thank you @japareaggae! Yeah, that is exactly the problem. Wild.

Hey @vivien, I really have no idea why this happens (an explanation would be awesome (bubby C coder)) but it's true. Removing the if broke colors from the INI file (tested with both i3 and i3's next branch).

**Comment by japareaggae** [comment]
My guess is that this is the same problem from issue #138: i3blocks reads an empty line and uses it to set the color, overwriting the `color` key on the config file. PR #143 fixed it, but only for persistent blocks.

**Comment by m3l7** [comment]
I have the same issue.
I can confirm that 701dd3f704509278183090f9b3e66c546d5e0d68 is the offending commit.
8f7097b359027bb3da189a0e89aaec32a1c5a9a6 doesn't solve for me, so I will return to c5b9734

**Comment by darko-mesaros** [comment]
Same issue with here with version 1.4-21-g017395f

**Comment by dkarwowski** [comment]
Yeah, this is reading an empty line when reaching the color and overwriting. I was able to fix this with this patch. Commit 701dd3f is the problem, since it's reading the empty lines and overwriting for color as well as the others. It's at least a fix.

```
diff --git a/src/block.c b/src/block.c
index 7a72c0c..67b68b4 100644
--- a/src/block.c
+++ b/src/block.c
@@ -163,7 +163,8 @@ block_update_plain_text(struct block *block, char *buf)
                 return;
 
 	linecpy(&lines, props->short_text, sizeof(props->short_text) - 1);
-	linecpy(&lines, props->color, sizeof(props->color) - 1);
+	if (*lines)
+		linecpy(&lines, props->color, sizeof(props->color) - 1);
 }
 
 static void
```

**Comment by japareaggae** [comment]
I have tried @dkarwowski's patch and I can confirm that it fixes this issue.

**Comment by vician** [comment]
@dkarwowski thanks, also works for me.

**Comment by Grelek** [comment]
Any update on this? Is @dkarwowski's patch anywhere upstream or do I have to include it by myself?

**Comment by Grelek** [comment]
@vivien @Airblader Is there any chance of including @dkarwowski's patch to i3blocks?

**Comment by Airblader** [comment]
@Grelek I don't maintain i3blocks, only i3blocks-gaps. If I find some time I'll test the patch and merge it to i3blocks-gaps, provided it works. I'd prefer @vivien merging it upstream, of course. :-)

**Comment by Grelek** [comment]
@Airblader Yes, I know you maintain only the gaps version but I mentioned both of you in one comment as I found it more efficient. ;) I can tell from my experience that the patch works but I didn't run any tests or something like that so I have literally no idea how well it integrates with the rest of the project.

**Comment by Airblader** [comment]
@Grelek I've pushed the commit to i3blocks-gaps.

**Comment by Nixpower** [comment]
@Airblader Oh wow, my bar is restored to full beauty, thank you :+1:

**Comment by Grelek** [comment]
@Airblader Thank you very much :+1:

**Comment by vivien** [comment]
Fix merged. Thank you guys for the report, patch, PR and test, sorry for the delay ;-)
