### ISSUE TITLE
Execute custom commands?

### ISSUE THREAD

**Issue by MaikKlein** [vivien/i3blocks#147]
```
[battery]
command=~/src/i3blocks/scripts/battery
interval=10

[wifi]
label= 
command=~/src/i3blocks/scripts/wifi
interval=10

[wifiid]
label= 
command=iwgetid -r

[datetime]
label= 
command=date '+%b %-d / %-l:%M %p '
```
I have no problems using the default scripts from i3blocks, but I am unable to use custom commands like 

```
[wifiid]
label= 
command=iwgetid -r
```
or
```
[datetime]
label= 
command=date '+%b %-d / %-l:%M %p '
```
wifiid and datetime are not displayed. I tested it on master and 1.4.

**Comment by kb100** [comment]
You must specify an interval on which the command should be run, e.g

    [datetime]
    label= 
    command=date '+%b %-d / %-l:%M %p '
    interval=1

use `interval=once` if you only want to run it once.
