### ISSUE TITLE
Long-Running Synchronous Command Never Resolves

### ISSUE THREAD

**Issue by bookercodes** [vivien/i3blocks#151]
I am aiming to output my download speed in the bar.

In order to determine my download speed I intend on using a command-line application called [**speed-test**](https://github.com/sindresorhus/speed-test).

Having installed the application, I can manually write:

``` bash
echo $(speed-test --json)
```

And after around 15 seconds, the command resolves with the following output:

``` json
{"ping":55, "download":71.2, "upload":18.5}
```

So far, so good!

Things only become problematic when I try and use the above command as the `command` value for a block:

```
[download]
command= echo $(speed-test --json)
interval=once
label=Icon
```

I can see the icon, but the command _never_ resolves:

![](https://i.imgur.com/EbWtW98.png)

Do you have any thoughts on what could be wrong here?

Thanks!

**Comment by Nycroth** [comment]
Why the echo?

**Comment by kb100** [comment]
Indeed, it seems like just using `command=speed-test --json` should work. Make sure speed test is outputting to stdout and that it outputs only one or two lines of text. Remember the format is

FULL_TEXT
SHORT_TEXT
COLOR

so if speed test outputs three lines and the third is not a valid color, then you may get no output.

**Comment by vivien** [comment]
I would do something like that to use the JSON result as a map for printing named arguments:
```` ini
[speed-test]
command=speed-test --json | head -1 | ruby -r json -n -e 'puts "Ping: %<ping>s Download: %<download>s Upload: %<upload>s" % JSON.parse($_, symbolize_names: true)'
interval=once
````
