### ISSUE TITLE
Increase the character limit for instance

### ISSUE THREAD

**Issue by Anachron** [vivien/i3blocks#152]
I've built a feed reader block and when the user passes a feed longer than 32 characters it will get cut off.

The problem is here:
https://github.com/vivien/i3blocks/blob/01a4f4a9ca1e3d0b3c95d1d62000ad8506bdff1a/include/block.h#L50

And an example need is here:
https://github.com/Anachron/i3blocks/blob/master/blocks/feed#L3-L7

**Comment by Nycroth** [comment]
I can comment on this also. I pass my password and hostname for mpd in the instance variable. I used to have a longer password but I trimmed it to meet this length. Mine was never a game changer so I ignored it but I do have a use case for arbitrary string length in the instance.

**Comment by kb100** [comment]
32 Does seem a bit short. I guess a bump to 256 would be more reasonable, but since URLs can be arbitrarily long you may want to add an option read the URL from a file :\

**Comment by Anachron** [comment]
@kb100 I have the current workaround with following redirection, so an URL shortener service can be used.

However, in other conditions (like path to a file) the 32 character limit can be a bit less.

**Comment by Anachron** [comment]
@vivien do you mind if I bump?

**Comment by vivien** [comment]
@Anachron I don't mind, please do. I'd gladly merge that. Hopefully in the next few weeks I'll be able to work on this and make all that dynamic. In the meantime, bumping the instance length seems reasonable.

**Comment by Anachron** [comment]
@vivien what would be the final solution, other than increasing the charlength?

**Comment by Anachron** [comment]
@vivien thanks a lot for the fix!
