### ISSUE TITLE
Pacman/AUR updates with colour?

### ISSUE THREAD

**Issue by ralpheeee88** [vivien/i3blocks#155]
o/...copied this from somewhere (cant remember)

[Updates]
label=AUR
command=sudo pacaur -Qu | wc -l
interval=1800

my question is if there is an update how can i change colour to indicate update/s available?

**Comment by kb100** [comment]
You may want to modify my blocklet https://github.com/vivien/i3blocks-contrib/tree/master/apt-upgrades to work for pacman. I'm sure some arch users would appreciate it if you submitted a pacman-upgrades blocklet to i3blocks-contrib.

**Comment by Anachron** [comment]
Or you can just use this one :+1: 
https://github.com/Anachron/i3blocks/blob/master/blocks/packages

**Comment by kb100** [comment]
@Anachron, consider contributing that to i3blocks-contrib!

**Comment by ralpheeee88** [comment]
super stuff!!!
