### ISSUE TITLE
[Request] make `click_n_command` config variables

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#165]
I have noticed that many blocklet scripts factor into two disjoint parts: the part that always runs, and the part that handles clicks/spawns secondary programs. A major shortfall of this is that it puts the burden of deciding the click action on the script writer, forcing them to guess what actions user may want to take, and provide command line switches to specify such actions etc. For some blocks there is one clear option and the script writer may want to do this, but it would be much more flexible and readable for the user if they could choose. For example,

```
[volume]
command=$SCRIPT_DIR/print_volume.sh
click_1_command=mixer-app
click_4_command=$SCRIPT_DIR/volume_up.sh
click_5_command=$SCRIPT_DIR/volume_down.sh
interval=5
```

instead of

```
[volume]
command=$SCRIPT_DIR/print_volume.sh --mixer=mixer-app
interval=5
```

This allows modularization of blocklet scripts, promotes user customization (picking their own mixer-app, etc.),  while remaining easy to understand and conforming to the existing config format. In addition, it allows blocklet developers to remove frivolous command line parsing code and repeated click parsing code.

@vivien, what are your thoughts on implementing this?

**Comment by vivien** [comment]
hi @kb100,

I do agree with you about the bloated command line arguments, I don't like them very much neither.

However I'm not a big fan of adding 5 new properties. You might have to add a few lines in your script, but at least all the logic if concentrated in there. Another trick is that you might want the default `command=` to execute anyway (after a click or not), or you may want to only execute the click action. For instance, printing the volume needs to execute anyway. Fetching mails on right click should stop after this action. I don't see a way to handle this except by adding a new property, which is a no-no ;-)

But I might have a compromise: I'm still thinking about the dynamic properties, and with this in place, you'll have a new common and natural way to pass arguments to the scripts. `_foo=bar` would give you the `$_FOO` environment variable. That way you can get your `$_CLICK_4_COMMAND`. The counter part is that your script would still have to handle it, something like:

```` sh
case $BLOCK_BUTTON in
  1) exec ${_CLICK_1_COMMAND:-true} ;; # do something (if command given) and exit right away
  2) ${_CLICK_3_COMMAND:-true} ;; # do something (if command given) and continue
  4) ${_CLICK_4_COMMAND:-amixer -q sset $_SCONTROL 3%+} ;;
  5) ${_CLICK_5_COMMAND:-amixer -q sset $_SCONTROL 3%-} ;;
  *) ;;
esac

amixer get $_SCONTROL | grep -E -o '[0-9]{1,3}?%' | head -1
````

With the following config:

```` ini
command=$SCRIPT_DIR/volume.sh
_scontrol=Master
_click_2_command=exec $SCRIPT_DIR/volume_mute.sh # in fact mute and exit right away
interval=5
````

Would that be acceptable for you?

**Comment by vivien** [comment]
I'm just thinking about a very generic script, event though that might not be useful ^^

```` sh
case $BLOCK_BUTTON in
  1) ${_LEFT_CLICK} ;;
  2) ${_MIDDLE_CLICK} ;;
  3) ${_RIGHT_CLICK} ;;
  4) ${_WHEEL_DOWN} ;;
  5) ${_WHEEL_UP} ;;
  *) ${_DEFAULT} ;;
esac
````

And a user config as such:

```` ini
full_text=click me
command=$SCRIPT_DIR/proxy_cmd.sh
_left_click=echo left
_right_click=echo right
````

Or even bloated but without any script:

````
command=case $BLOCK_BUTTON in 1) ${_LEFT_CLICK} ;; 2) ${_MIDDLE_CLICK} ;; 3) ${_RIGHT_CLICK} ;; *) ${_DEFAULT} ;; esac
````

**Comment by kb100** [comment]
I like the idea of dynamic properties a lot more than adding 5 fixed properties. As stated, I would be happy with what you suggest. I have an additional whim though. Introduce one new property `_handle_clicks=auto|manual` which is set to `auto` by default. If `handle_clicks` is set to `auto`, then execute `_CLICK_1_COMMAND`, if set, in parallel to the script when a click button 1 occurs.

I suggest this because many click commands function independently of the main script, e.g. by spawning some external gui application. This effectively puts the cookie cutter click handling code into `i3blocks`, relieving script writers from putting that block of code at the top of every script.

If building the click handling into i3blocks is too extreme, what about providing a wrapper script for click handling, so that users could write, e.g.

    [example]
    command=handle_clicks example.sh args
    _left_click=auxiliary.sh #handled by handle_clicks, not example.sh
    # ... other props for example.sh

This would be an easy way for anyone to add the simplest click spawning functionality to any script, while still allowing more sophisticated scripts to manually do the click handling.

**Comment by vivien** [comment]
That `_handle_clicks` property won't work, because with the dynamic properties I suggested, `_CLICK_1_COMMAND` would be just a normal variable passed by i3blocks to the forked scripts, as `_FOO` if you added a `_foo=bar` property.

Another reason why I'm not convinced by putting this handling code in i3blocks, is: what do we do with the output of the command executed by a click? Sometimes that is totally external and you don't care about it, sometimes you do care (for instance the default behavior is to re-execute a block command on click).

I prefer your idea of providing a wrapper to the user (that'd end up in i3blocks-contrib). But if I'm not mistaken, this script would basically be what I suggested above in my second comment? so you'd let the user provide some `_left_click` or `_default` commands. The user would even be able to control the flow of its block, by prepending `exec ` or not in front of its custom commands.

To be more precise, I'd say:

```` sh
#!/bin/bash

# Prepend a command with "exec " in the i3blocks config if you don't want
# the "_default_command" to be executed (if given) after a mouse action.
# For example, this block prints number of unread mails, fetch mails and 
# update count on right click, and only open mailer on left client:
#
#     command=handle_clicks print_unread_mail_number.sh
#     _left_click_command=exec open_mail_client.sh
#     _right_click_command=fetch_mails.sh
#     interval=300

case $BLOCK_BUTTON in
  1) ${_LEFT_CLICK_COMMAND} ;;
  2) ${_MIDDLE_CLICK_COMMAND} ;;
  3) ${_RIGHT_CLICK_COMMAND} ;;
  4) ${_WHEEL_DOWN_COMMAND} ;;
  5) ${_WHEEL_UP_COMMAND} ;;
  *) ;;
esac

${_DEFAULT_COMMAND}
exit
````

`$_DEFAULT_COMMAND` could indeed be passed either as the wrapper's first argument, or as a `_default_command` property, it doesn't really matter.

If a click action should update the block content, `$_DEFAULT_COMMAND` must be empty.

**Comment by kb100** [comment]
Alright, I think the wrapper idea is the way to go.

**Comment by vivien** [comment]
There are other ideas, like a wrapper which uses mouse actions to toggle an argument from a list before passing it to a command (e.g. `df -h`). Left click = first arg, right click = last arg, wheel up/down = iterate forward/backward. Or writing a progress bar wrapper.

Another great use of dynamic properties that I have in mind (in addition to supporting @Airblader's i3-gaps fancy properties ;-)) is to provide a common interface for themes, with 2 global variables: `_color_good` and `_color_bad`.

This is doable today with command line arguments though. But these dynamic properties would simplify the wrappers a lot.

**Comment by vivien** [comment]
Well it looks like this is finally implemented! I'm closing the issue. :-)

**Comment by zoj613** [comment]
This there documentation for customizing command to run when left/right-clicking the mouse, but still get to use the `command` option for the "default" command? I cant find any after searching.
