### ISSUE TITLE
Support for streaming blocks

### ISSUE THREAD

**Issue by Kilobyte22** [vivien/i3blocks#169]
I'd really apprechiate support for streaming blocks. What does this mean? A block gets started once and keeps sending out lines. After every third line (long message, short message, color) it would display the sent data. The script usually would then perform a sleep until it has data to display again.

Example:

```
Current Status: stuff
stuff
#FFFFFF <this line is followed by lets say a 3 minute break>
Current Status: other_status
other_status
#FFFFFF
```

Why?
Sometimes the block needs to keep state internally. For example a block that scrolls  through different values. You can write this state to disk, but that makes things way harder. You can also keep a daemon running in the background, but that is really overkill. This is a simple change that would make way easier

**Comment by kb100** [comment]
This behavior is already possible with the config options

    format=json
    interval=persistent

**Comment by Kilobyte22** [comment]
I see, thats pretty nice and good to know. Persistent does require json though?

**Comment by kb100** [comment]
Persistent does not require json, but if you do not use json then you will only be able to specify the full text, not the full text and short text. You can still get colors with pango formatting.

**Comment by serch037** [comment]
Could you provide a MWP please?

**Comment by Kilobyte22** [comment]
I don't know what you mean by that, couly you please explain?

**Comment by kb100** [comment]
MWP (minimal working program?)

    [test]
    command=while true; do date; sleep 1; done
    interval=persist

With colors:

    [test]
    command=while true; do echo "<span color='blue'>$(date)</span>"; sleep 1; done
    interval=persist
    markup=pango

Full text and short text:

    [test]
    command=while true; do echo "{\"full_text\":\"$(date)\",\"short_text\":\"today\"}"; sleep 1; done
    interval=persist
    format=json
