### ISSUE TITLE
Wired check

### ISSUE THREAD

**Issue by deimosfr** [vivien/i3blocks#17]
Hi,

Here is a check for wire connection. It is smaller, detect if the device is present (nice for notebook or any laptop that needs a sub ethernet adaptator).

https://gist.github.com/deimosfr/10234327

Please let me know what do you think about it.

**Comment by vivien** [comment]
We split the *network* script in 3 scripts: *iface*, *wifi* and *bandwidth*, for simplicity. I'm closing this PR then, thanks.
