### ISSUE TITLE
Volume block adjust the wrong device

### ISSUE THREAD

**Issue by R0flcopt3r** [vivien/i3blocks#170]
When I try to adjust the volume, it changes the volume on my HDMI sound device. I have a USB headset which is the one I use and is the one that needs to be adjusted.

I use pulseaudio, and I've set "pulse" on line 25 in the volume script, nothing else is changed.

**Comment by jpleau** [comment]
I have this issue, but I think this is an issue with pulse not switching the "default device"

Install pavucontrol, run it, and in the devices tab, make sure your USB is set to default. The blocklet should work then.

I haven't found another way to fix it yet

**Comment by vivien** [comment]
Looks like it's fixed, thanks!
