### ISSUE TITLE
No battery, CPU ussage and Volume

### ISSUE THREAD

**Issue by Ro6afF** [vivien/i3blocks#179]
When I run i3blocks | grep -i cpu ti prints this:
`ERROR block_reap:329: [battery] bad exit code 1
ERROR block_reap:329: [cpu_usage] bad exit code 2` in i3bar it doesnt show baterry, CPU usage and vloume. And the IP address isnt colored.

**Comment by kb100** [comment]
Would you please run the battery and cpu_usage blocks from the command line? They should be in `/usr/local/libexec/i3blocks`

**Comment by egyptianbman** [comment]
I'm having the same issue on a fresh install:

```
{"version":1,"click_events":true}
[[]
,[{"full_text":""}]
ERROR block_reap:329: [volume] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [memory] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [disk] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [cpu_usage] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [disk] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [load_average] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [memory] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [wifi] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [bandwidth] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [disk] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [iface] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [disk] bad exit code 127
,[{"full_text":""}]
ERROR block_reap:329: [disk] bad exit code 127
,[{"full_text":""}]
,[{"full_text":""},{"":"","full_text":"2016-03-29 10:44:49","name":"time","separator_block_width":15,"markup":"none"}]
ERROR block_reap:329: [disk] bad exit code 127
,[{"full_text":""},{"":"","full_text":"2016-03-29 10:44:49","name":"time","separator_block_width":15,"markup":"none"}]
ERROR block_reap:329: [disk] bad exit code 127
,[{"full_text":""},{"":"","full_text":"2016-03-29 10:44:49","name":"time","separator_block_width":15,"markup":"none"}]
```

Running the separate services, I get:
```
$ /usr/local/libexec/i3blocks/cpu_usage
18.78%
18.78%
```

```
$ /usr/local/libexec/i3blocks/disk -d /mnt/5tb1
612G
612G
```

etc.

**Comment by kb100** [comment]
Exit codes 2, and 127  are special special shell exit codes for permissions problems/command not found. This indicates that your $PATH might be messed up or the user running i3blocks doesn't have read permission of the scripts. Can you post your i3blocks config and the section of your i3 config relating to i3blocks?

**Comment by egyptianbman** [comment]
Gotcha.  I copied the config file from the repo which had the following line:
```
command=$SCRIPT_DIR/$BLOCK_NAME
```
I changed it to:
```
command=/usr/local/libexec/i3blocks/$BLOCK_NAME
```
and everything worked as expected.

I'm not sure how `$SCRIPT_DIR` is fed into the config.

In my `.config/i3/config` I have:
```
status_command i3blocks -c ~/.config/i3/blocks
```

**Comment by Ro6afF** [comment]
@kb100 sorry for the late response.
First the scripts are in /usr/libexec/i3blocks .
So, this is the output of each of them(these which prints errors):
`./cpu_usage
Can't exec "mpstat": No such file or directory at ./cpu_usage line 36.
Died at ./cpu_usage line 36.
`

`./battery 
sh: acpi: command not found
Use of uninitialized value $acpi in pattern match (m//) at ./battery line 32.
Use of uninitialized value $acpi in concatenation (.) or string at ./battery line 33.
`
 
`./volume
./volume: line 36: amixer: command not found
./volume: line 45: amixer: command not found
./volume: line 50: amixer: command not found
`

**Comment by anders-larsson** [comment]
@kb100 you need to install the packages providing mpstat, acpi and amixer for your Linux distribution. Once these applications is available you should be able to run the blocks.

**Comment by kb100** [comment]
@egyptianbman $SCRIPT_DIR is not fed into the config automatically, it is meant to be a place holder for where the actual script goes. You can feed it in manually with e.g.

    status_command SCRIPT_DIR=~/scripts/i3blocks i3blocks

@Ro6afF you need the following packages: sysstat, acpi, alsa-utils. The first two are mentioned in the main README https://github.com/vivien/i3blocks

**Comment by Ro6afF** [comment]
@kb100 Thank you!
