### ISSUE TITLE
errno.h no such file or directory [Solved]

### ISSUE THREAD

**Issue by Lunarised** [vivien/i3blocks#180]
Hi. I am new to i3 and wanted to change to i3 blocks. However, i have found a problem which has stumped me, and its during the installation. I use git to install i3blocks, then i change directory into i3blocks. However "make clean all" is encontering an error (See below)
![2016-04-06-011441_1600x900_scrot](https://cloud.githubusercontent.com/assets/18286813/14282944/11c1d7a0-fb95-11e5-9778-98f8f7ba4281.png)

Does anyone know what might be causing this problem, or steps to take to fix it?
Cheers!

**Comment by kb100** [comment]
errorno is a a C standard library. If this file wasn't found then you probably haven't installed the C standard library, libc6-dev package on debian. This should have been a dependency of any compiler that you installed though.

**Comment by Lunarised** [comment]
Thakyou very much, installing libc6-dev fixed the issues i was havng :)
