### ISSUE TITLE
Pango markup shows in up in bar rather than rendered content

### ISSUE THREAD

**Issue by justbuchanan** [vivien/i3blocks#181]
Here's a screenshot of my bar: http://imgur.com/qAnR6eI.

My i3blocks config is;

~~~{.sh}
[date]
command=$SCRIPT_DIR/scripts/now.py
interval=20
~~~

Where `now.py` is below.  It's a little verbose, but I'm using these functions for several scripts.

~~~{.py}
TEXT_COLOR = '#000000'
ICON_COLOR = '#4C88B3'

def pango(text, color=TEXT_COLOR, size=None):
    params = {'foreground': color}
    if size != None: params['font_size'] = size
    p = " ".join("%s='%s'" % (k,v) for k, v in params.items())
    return "<span %s>%s</span>" % (p, text)

def icon(font_awesome, color=ICON_COLOR):
    return pango(font_awesome, color, 'large')


now = datetime.datetime.now()
txt = pango(now.strftime('%a %m/%d %H:%M'))

ic = icon('')

print("%s %s" % (ic, txt))
~~~

The strange thing is that this works completely fine on one of my computers, but not the other.  I'm wondering if it's some sort of font issue, but I can't seem to track it down.  Any suggestions are greatly appreciated.

**Comment by bendem** [comment]
Missing `markup=pango` in your config?

**Comment by justbuchanan** [comment]
I had `markup=pango` in there before, but then I see no text at all.  I can see the icon though.

**Comment by justbuchanan** [comment]
Oh wow, it turned out that my text was white on a white background... it works great now.  Thanks!

**Comment by justbuchanan** [comment]
For some reason my `#000000` color didn't show up at all, but if I do `#010101` it shows up as ~black just fine.

**Comment by bendem** [comment]
Sounds related to https://github.com/i3/i3/issues/2294

**Comment by justbuchanan** [comment]
Thanks for the link!  That looks like the exact issue I'm having.  They reported it to upstream, so I'll just wait for an update and use something other than `#000000` for now.
