### ISSUE TITLE
label not treated as pango even if markup=pango specified

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#182]
Certain fontawesome icons show up garbled if you don't explicitly specify fontawesome as the font, so I would like, e.g. 

    label=<span font='FontAwesome'>  </span>
    markup=pango

to work.

**Comment by qvint** [comment]
It's because `label` is [limited](https://github.com/vivien/i3blocks/blob/6a345440853d1cd16cef7096ffc636bed161fd91/include/block.h#L58) to 32 chars.
