### ISSUE TITLE
Support background as a key

### ISSUE THREAD

**Issue by nicklan** [vivien/i3blocks#183]
It appears that i3bar now supports a background key to change the background color of a block.  It would be great if i3blocks supported that too.

I know there's the option of using `<span>`s with pango, but the problem there is, how do you use any of the builtin blocks and wrap their output in a span?  You can prefix in the label key, but without a `</span>` i3bar doesn't display anything.  If there was an append key to append to full_text, that would be fine too.

Thanks!

**Comment by kb100** [comment]
If your block always outputs 3 lines, i.e. full text, short text, color, you can use

    command=/path/to/command | awk 'NR%3!=3{print "<span color=\"blue\">"$0"</span>";}1{print $0}'

For blocks that just output one line

     command=/path/to/command | awk '{print "<span color=\"blue\">"$0"</span>"}'

Modify the `<span color="blue">` as needed to fit your formatting

**Comment by nicklan** [comment]
Yep, that works nicely, thanks.

Still seems a bit convoluted and might be nice to have a simpler way to achieve the same effect.

**Comment by kb100** [comment]
Agreed, i3blocks should support all the keys that i3bar does, so this is just a quick fix for you.

**Comment by vivien** [comment]
Thanks for the update on i3bar! Added support for the new 'border' key as well.
