### ISSUE TITLE
Missing dep in PKGBUILD i3blocks-git (Archlinux)

### ISSUE THREAD

**Issue by x11tete11x** [vivien/i3blocks#184]
Sorry for put the issue here but i cant log in in AUR :/

testing i3blocks-git cpu_usage dont work, after a little debug i found that needs sysstat as dep

thx!

**Comment by bchretien** [comment]
It is already listed as an optional dependency, see [here](https://aur.archlinux.org/packages/i3blocks-git):

> sysstat (optional) – For example cpu_usage script

**Comment by x11tete11x** [comment]
El El jue, 19 de may de 2016 a las 9:15 a.m., Benjamin Chrétien <
notifications@github.com> escribió:

> It is already listed as an optional dependency, see here
> <https://aur.archlinux.org/packages/i3blocks-git>:
>
> sysstat (optional) – For example cpu_usage script
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vivien/i3blocks/issues/184#issuecomment-220306818>
>
Ohhh i see, sorry!, my mistake
