### ISSUE TITLE
blocklet disappearing

### ISSUE THREAD

**Issue by jhsul** [vivien/i3blocks#187]
Hi,

I've been trying to make a shortcut on my statusbar for spotify. The blocklet in my .i3blocks.conf looks like this:

```
[spotify]
command=spotify
full_text=
separator=false
```

It definitely, but when I close the spotify window the blocklet disappears from the bar. Do you have any ideas as to what might be causing this? If this helps, I am using the i3blocks-gaps fork. Maybe that's the source of the problem?

thanks

**Comment by kb100** [comment]
Get rid of full_text and put

    [spotify]
    interval=once
    command=echo  && i3-msg "exec spotify" >/dev/null

**Comment by jhsul** [comment]
Thank you so much!

Is there any way to set it up so that it doesn't

**Comment by jhsul** [comment]
Thank you so much!

Is there to set it up so that it doesn't open spotify on startup, though?

**Comment by kb100** [comment]
echo  && if [[ "$BLOCK_BUTTON" == 1 ]]; then i3-msg "exec spotify" >/dev/null; fi

**Comment by jhsul** [comment]
Thank you!!
