### ISSUE TITLE
Button simulate

### ISSUE THREAD

**Issue by dvino** [vivien/i3blocks#189]
I simulate a button like this:
[button]
full_text=Some text
command=some_program

When I press the button, opens the program. But after the program is closed, the button disappears.

**Comment by kb100** [comment]
Full text is overwritten by command. The block is disappearing because your command outputs no text. The proper way to implement a button is

    [button]
    interval=once
    command=echo "Click me"; [[ -z "${BLOCK_BUTTON}" ]] || /path/to/script

**Comment by kb100** [comment]
Also note that if your script does not terminate quickly (e.g. if it starts a gui program) then it would be called with i3-msg exec so as to not freeze the bar.

**Comment by dvino** [comment]
Thank you!
It's work! 
In FAQ is wrong information. Can you correcr it?

**Comment by kb100** [comment]
FAQ corrected, thanks for pointing this out.
