### ISSUE TITLE
Where is /usr/lib/i3blocks/disk?

### ISSUE THREAD

**Issue by markvincze** [vivien/i3blocks#191]
In multiple sample configurations I see the command `/usr/lib/i3blocks/disk` being used, but on my computer that file is not there (there isn't any `/usr/lib/i3blocks` directory).

I'm on Ubuntu 16.04, I tried both installing `i3blocks` with `apt-get`, and also tried building from source.
How can I get the i3blocks libs?

**Comment by markvincze** [comment]
It turned out they're in `usr/shared/i3blocks`.

**Comment by jpleau** [comment]
Yes, architecture independent files are located in /usr/share on Debian and derivatives. Otherwise they would be in /usr/lib/<arch>/i3blocks
