### ISSUE TITLE
Click with no output ends Block

### ISSUE THREAD

**Issue by MorphBonehunter** [vivien/i3blocks#196]
Hello,
maybe i'm wrong but as i understand the documentation an i3block block should persist with the "full_text" if the command doesn't return anything?
So this does not work for me, when i tried this with the shutdown_menu from the contrib repo (i've used the example config in the repo).
After the first click the Block disappears from i3bar an could not used again.
So for testing i did an simple example.
I've define an simple section (only this is in the config, no global or something else):

```
[click]
full_text=click
command=true
```

So from my understanding if i click nothing should happen and the block (the text "click") should persist an could use it again.
This does not happen, if i click the "button" disappear.
So i enable logging and sees the following lines on click:

```
DEBUG sched_start:177: received signal 29 (I/O possible)
DEBUG click_parse:65: parsed click: name= instance= button= x= y=
DEBUG click_parse:65: parsed click: name=click instance= button=1 x=1891 y=4
DEBUG bar_poll_clicked:62: [click] clicked
DEBUG block_spawn:295: [click] forked child 1377 at 1470129029
DEBUG sched_start:177: received signal 17 (Child exited)
DEBUG bar_poll_exited:121: [click] exited
DEBUG block_reap:315: [click] process 1377 exited with 0
DEBUG block_update:231: [click] updated successfully
DEBUG json_print_bar:147: [click] no text to display, skipping
```

So did i something wrong or is this an bug?

**Comment by doenietzomoeilijk** [comment]
I ran into the same issue as you. As a workaround, I changed the command in my config to `command=$SCRIPT_DIR/shutdown_menu; echo "Quit"` (Where "Quit" is the `full_text` as well).

**Comment by vivien** [comment]
Hi @MorphBonehunter, with your click example, I have the exact behavior you described. That might have been fixed in master. Are you able to give it a test?

**Comment by MorphBonehunter** [comment]
Hi @vivien, i'm at de1d46a8d80cdd9d97178906b6c2e87ab764960a and it doesn't work for me.
As the last commit is "just" an Makefile addition i guess it does not make any difference?

**Comment by vivien** [comment]
You are correct, the commit causing this is 701dd3f from #109. People want to consider an empty line as a valid output. @kb100 pointed out the alternative way to simulate a button in #189.

I am wondering if I should consider this a regression or not...

**Comment by MorphBonehunter** [comment]
Ok, that is an solution i think.
I'm not sure if this should handled as an regression, i was confused on reading the http://vivien.github.io/i3blocks/ and found in the interval section the "which is useful to simulate buttons" on unspecified or 0 so i thought this must be the right way.

**Comment by vivien** [comment]
You are right, the documentation for this part is out of date. I'll fix it. Other than that, I'm wondering if it is comprehensible and intuitive enough for a user to consider writing a button like this:

```` ini
[button]
interval=once
command=echo button: $BLOCK_BUTTON
````
or 
```` ini
[lock]
interval=once
command=[[ -n $BLOCK_BUTTON ]] && i3-msg -q exec i3lock; echo Lock
````
or 
```` ini
[click]
full_text=Not clicked yet
command=echo Clicked!
````

versus the previous behavior:

```` ini
full_text=Lock
command=i3-msg -q exec i3lock
````

I'm curious to know @kb100 and @Airblader thoughts on this... Others welcome for sure :-)

**Comment by Airblader** [comment]
I agree that this is an unfortunate breakage but I think the new behavior is better. There are legitimate use cases for empty output and I don't see a good way to achieve this in a different way. Buttons, however, can still be created with a minor change. 

If anything we should find a better way to create buttons, IMHO. Printing an empty line for empty output is easily the most intuitive way to achieve empty output, we should keep that.

**Comment by kb100** [comment]
Agreed that empty lines are needed. As long as the documentation is clear I think newbies will be able to cope just fine.

**Comment by vivien** [comment]
I agree with both of you. Directly using `full_text` is a special case where no command is specified. When provided, relying on the command output is more intuitive.

**Comment by MorphBonehunter** [comment]
So i think when the docu is fixed this issue could be closed.
