### ISSUE TITLE
Feature Request: Xresources assignments

### ISSUE THREAD

**Issue by donniebishop** [vivien/i3blocks#198]
Some months ago, there was a commit pushed to the i3-gaps development branch a feature to reference values set in Xresources and use them in i3's config file.

I am requesting this feature be implemented in i3blocks, so as to reference color values from theme files, font configurations, etc.

This feature was implemented using `xcb-util-xrm`, but I'm not certain if that would be necessary as a dependency here.

**Comment by Airblader** [comment]
I've prepared a quick and dirty patch. Of course this needs some changes to not reconnect and recreate the database every single time and if @vivien accepts this feature at all, he'd probably want to make the dependency a compile-time switch, but anyhow, it at least shows the basic workings (not extensively tested):

````
diff --git a/Makefile b/Makefile
index 1229346..766c040 100644
--- a/Makefile
+++ b/Makefile
@@ -29,6 +29,8 @@ CPPFLAGS += -DSYSCONFDIR=\"$(SYSCONFDIR)\"
 CPPFLAGS += -DVERSION=\"${VERSION}\"
 CFLAGS += -std=gnu99 -Iinclude -Wall -Werror=format-security
 
+LIBS := -lxcb -lxcb-xrm
+
 OBJS := $(wildcard src/*.c)
 OBJS := $(OBJS:.c=.o)
 
@@ -43,7 +45,7 @@ debug: CFLAGS += -g
 debug: $(PROGRAM)
 
 $(PROGRAM): ${OBJS}
-	$(CC) $(LDFLAGS) -o $@ $^
+	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)
 	@echo " LD $@"
 
 man: $(PROGRAM).1
diff --git a/src/ini.c b/src/ini.c
index 62430cc..27af0ee 100644
--- a/src/ini.c
+++ b/src/ini.c
@@ -22,6 +22,8 @@
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
+#include <xcb/xcb.h>
+#include <xcb/xcb_xrm.h>
 
 #include "bar.h"
 #include "block.h"
@@ -73,7 +75,8 @@ static int
 parse_property(const char *line, struct properties *props, bool strict)
 {
 	char *equal = strchr(line, '=');
-	const char *key, *value;
+	const char *key;
+        char *value;
 
 	if (!equal) {
 		error("malformated property, should be a key=value pair");
@@ -83,11 +86,26 @@ parse_property(const char *line, struct properties *props, bool strict)
 	/* split key and value */
 	*equal = '\0';
 	key = line;
-	value = equal + 1;
+        if (strncmp(equal + 1, "resource:", strlen("resource:")) == 0) {
+                int screen;
+                xcb_connection_t *conn = xcb_connect(NULL, &screen);
+
+                xcb_xrm_database_t *database = xcb_xrm_database_from_default(conn);
+                char *resource;
+                xcb_xrm_resource_get_string(database, equal + 1 + strlen("resource:"), NULL, &resource);
+                value = strdup(resource);
+                free(resource);
+                xcb_xrm_database_free(database);
+
+                xcb_disconnect(conn);
+        } else {
+                value = strdup(equal + 1);
+        }
 
 #define PARSE(_name, _size, _flags) \
 	if ((!strict || (_flags) & PROP_I3BAR) && strcmp(key, #_name) == 0) { \
 		strncpy(props->_name, value, _size - 1); \
+                free(value); \
 		return 0; \
 	}
 
@@ -95,6 +113,7 @@ parse_property(const char *line, struct properties *props, bool strict)
 
 #undef PARSE
 
+        free(value);
 	error("unknown key: \"%s\"", key);
 	return 1;
 }
```

**Comment by vivien** [comment]
That might be interesting... Do you have an example of such usage and what value this brings?

That won't be for now though, since I'm slowing preparing a new version, but I keep this issue open for the tracking. Thanks.

**Comment by Airblader** [comment]
Personally I'd use this to get rid of duplicating the color values into the i3blocks config. That makes maintaining the theme of my machine much easier (and was the motivation for implementing this in i3 as well). 

People could also use it to do host specific things in the config quite easily. I see that as a rare minor use case though.

**Comment by vivien** [comment]
I guess having flexible mechanisms to centralize color theme is an attractive feature to most users. Using Xresource is indeed one of them. I'll keep that in mind. Thanks

**Comment by donniebishop** [comment]
I can't really comment on this much since I've been using polybar for the last year or so. The proposed workaround seems like it should work fine, but to be honest I can't really speak on this as well as I used to

**Comment by Airblader** [comment]
The workaround feels a bit too ugly for my taste, though I understand not wanting a dependency. Ultimately anyone can write any kind of client to get the resources from whatever source they want and pass it to i3blocks to forward it further to i3bar, and I think that's fine. The proposal was mostly to make this more comfortable to users who aren't experienced script writers and to avoid users having to do this on their own all the time, I guess. :-)

**Comment by vivien** [comment]
Well I think if one is centralizing color definitions in an Xresources file, there's good chance (s)he's already an experienced user ;-)

The thing is I want users to write their own framework, placing all their scripts in a personal repository if they want to, or contribute to the official one (i3blocks-contrib) shipped with their distro packages. Some won't use the default scripts at all and will want only minimalistic command lines in their config, others will want to build their own framework from scratch, wrapping block commands in scripts supporting Xresources, pango or whatever abstraction. That is all fine.

For this reason I'd prefer to maintain i3blocks as simple as possible, as long as the workaround is not hacky, and is simple and intuitive enough not to bother the user.

**Comment by Airblader** [comment]
> Well I think if one is centralizing color definitions in an Xresources file, there's good chance (s)he's already an experienced user ;-)

From my experience that very much isn't true (people use X resources for tools that support using it), but again, I do get your point and understand it. We should probably close this then?

**Comment by vivien** [comment]
OK I understand. The thing is defining our abstraction for colors can be a PITA and I'd like to avoid that if possible. I'm closing the issue for now, but we can reopen it if we figure out that user defined colors in i3blocks becomes a nightmare and needs some kind of standardization. Thank you!

**Comment by kgilmer** [comment]
I may be missing something here (I usually am), so want to clarify;  As it stands, I cannot directly reference Xresources from within i3blocks.conf.  These "frameworks" mentioned above are things that would perform some transforms on a template i3blocks.conf and replace tokens with values from Xresources?  Or is there something simpler I'm missing?

I can certainly understand your motivations for keeping i3blocks simple but as an integrator, it means I need add this complexity into an intermediary tier.  Complexity that will be directly exposed to the user, and open up the annoyance and all the edge cases of people modifying the transformed/generated config files only to have them be magically destroyed upon some subsequent package update.

Xresources is a very powerful facility (because of the preprocessor support) for configuration and IMHO the trade off of more complexity inside of i3blocks vs less complexity overall is worth it for users.  @Airblader 's patch looks pretty straightforward and maybe simple enough for me to integrate into a fork.  If that works out I'll update this ticket.

**Comment by Airblader** [comment]
Please don't take that patch unchanged, though, it's pretty wasteful in terms of resources as-is. :-)
