### ISSUE TITLE
NotoColorEmoji.ttf

### ISSUE THREAD

**Issue by webavant** [vivien/i3blocks#202]
Apologies if this is a cairo bug. The embedded bitmaps (or maybe SVG) from the Noto Color Emoji font are displayed in reverse color. 
![i3blocks1](https://cloud.githubusercontent.com/assets/4877688/18237817/da25554c-72ea-11e6-81bf-256f93bb60f1.png)

**Comment by vivien** [comment]
I'm not sure to know what happens here. Feel free to reopen the issue if the issue persists, thanks!
