### ISSUE TITLE
Missing tray icon backgroud redraw

### ISSUE THREAD

**Issue by lindhe** [vivien/i3blocks#204]
Tray icons that have transparent backgrounds, the background is not properly redrawn after placing the icons. This is causing varying degrees of old junk behind the icons.

Here you can clearly see some text hidden behind the Dropbox icon and a Telegram icon hidden behind the ownCloud icon.

![screenshot from 2016-09-08 19-33-51](https://cloud.githubusercontent.com/assets/7773090/18359659/3190c164-75fb-11e6-9235-c24411b83e59.png)

I'm running:
* Arch Linux 4.7.1-1-ARCH
* i3 4.12
* i3blocks 1.4

**Comment by kb100** [comment]
@vivien should confirm this, but I thought i3blocks doesn't even get to touch tray icons (run i3blocks from command line and you will not see any info about tray icons in there),  this is entirely handled by i3bar itself. If this is the case, this bug should be reported as a bug to https://github.com/i3/i3.

**Comment by lindhe** [comment]
If that is the case, the issue should indeed be moved there. I'm waiting on confirmation.

**Comment by vivien** [comment]
@kb100 is correct, the tray output is a property of i3bar, see: http://i3wm.org/docs/userguide.html#_tray_output

i3blocks cannot do much about it, closing the issue.

**Comment by lindhe** [comment]
For those curious on the follow up: https://github.com/i3/i3/issues/2447
