### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ImAWizardLizard** [vivien/i3blocks#207]
On my laptop I have been experiencing high CPU usage coming from my i3bar. Specifically the i3blocks program is consuming a high amount of CPU and draining my battery fast. When I use the default i3status, there seems to be no high CPU usage or fan speed, as well as the normal battery lifetime.  Could it be due to the contents of my i3blocks.conf file? I used htop to analyse my CPU usage and it said i3bar was consuming around 12% of my CPU with it using i3blocks.

**Comment by ImAWizardLizard** [comment]
SOLVED:

Don't use "repeat" as your interval

**Comment by omarzina** [comment]
Had same problem, switching from "repeat" to something else fixed it, but what should I put in a block like volume status?

**Comment by 8carlosf** [comment]
I personally use `interval=once` and then send a signal every time I change volume, so the refresh is instante and only made then needed.

Feel free to take a lokk at my configs:

https://github.com/8carlosf/dotfiles/blob/master/i3/.i3/i3blocks.conf#L90-L100

https://github.com/8carlosf/dotfiles/blob/master/i3/.i3/config#L239-L241

**Comment by omarzina** [comment]
Worked like a charm. Thanks.
