### ISSUE TITLE
Use signal with interval=persist?

### ISSUE THREAD

**Issue by justbuchanan** [vivien/i3blocks#210]
Is this possible?  It doesn't seem to be working when I try it.

My use case is that I have a persistent script that prints information when it receives a notification (in this case that volume changed).  I would like it to reload colors from xresources every time i3 reloads.  I call `pkill -RTMIN+1 i3blocks` after reloading i3 so that it will signal my persistent item script, which will reload colors.  I have `signal=1` set for my block as well as `interval=persist`, but my script doesn't seem to receive the signal.

Thanks!

Edit: here's a gist containing an example: https://gist.github.com/justbuchanan/0b7ef521049bfd38b8ee9ed67aeacc38

**Comment by justbuchanan** [comment]
After reading the docs again, I think I misunderstood what the `signal` option does.  Rather than signaling the script, it re-executes the script.

Is there a way to notify a script when i3blocks reloads without re-launching the script?

**Comment by vivien** [comment]
Indeed when *i3blocks* receives the signal `RTMIN+1`, it re-executes blocklets defined with `signal=1`, if their command aren't already spawned.

If you want your script to reload colors upon reception of a signal, why don't you signal it directly after reloading i3?

**Comment by justbuchanan** [comment]
Thanks for the reply!

I ended up using [i3ipc](https://github.com/acrisci/i3ipc-python) to listen for i3's `barconfig_update` notification, which seems to be working well.
