### ISSUE TITLE
battery block using upower instead of acpi/apm

### ISSUE THREAD

**Issue by pluralitas** [vivien/i3blocks#211]
I have installed i3 using crouton on my samsung s3 arm chromebook. Unfortunately, acpi or apm does not work for the crouton because there is the chromium-os power manager involved. The only way that i could get the battery information is from upower.

I understand that the battery block of i3blocks gets the battery information from the acpi/apm which in my case it does not work. I have no proficiency in the coding language that i3blocks used therefore i am unable to create a custom script for myself. I would appreciate if anyone could write me a code with a few comments so that i could have somewhere to start learning to write these. Thank You.

The screenshot of the data i could collect from upower is here: 
![screen](https://cloud.githubusercontent.com/assets/22367172/20203690/72075902-a804-11e6-8697-f11ea27901d8.jpg)

**Comment by kb100** [comment]
For your temporary relief:

    [battery]
    label=BAT
    command=upower -i /org/freedesktop/Upower/devices/battery_sbs_104_00b | grep precentage |  grep -o '[[:digit:]]\+%$'
    interval=30
