### ISSUE TITLE
disk block alert_low argument

### ISSUE THREAD

**Issue by sixtyfive** [vivien/i3blocks#215]
the disk block comments say it can take an "optional argument" to set the value for when it turns red, but doesn't say what that argument's name is. looking at the source code of the block, i could only suspect it to be "alert_low" but that causes and error. googling doesn't help either, so it would be lovely to get that info somehow :)

**Comment by kb100** [comment]
ALERT_LOW="${1:-10}"

This means "create a variable `ALERT_LOW` whose value is `$1` (positional argument), or `10` if `$1` is not given.

The correct usage is then, e.g.

    [disk]
    command=/path/to/script/disk 5
    instance=/directory/to/watch
    interval=60

**Comment by sixtyfive** [comment]
Thank you so much! I just didn't realize that "argument" meant "argument to whatever is given as 'command'". Works wonderfully now :+1:
