### ISSUE TITLE
min_width padding should be added after the label, not including it

### ISSUE THREAD

**Issue by roobre** [vivien/i3blocks#219]
I've found that the `min_width` directive includes the label size when calculating the actual minimum width of a block. This is certainly counter-intuitive, and cause problems with icon fonts (like ttf-font-awesome), as these characters usually don't have the same width as alphanumeric characters.

This behaviour also cause the label to move right and left, instead of staying still. See attached pictures of the `cpu_usage` script for an example:

![tmpopgl5r-save](https://cloud.githubusercontent.com/assets/969721/22626281/298272fe-ebaa-11e6-88d7-21f326e3b946.png)
![tmpkwanzg-save](https://cloud.githubusercontent.com/assets/969721/22626282/2987d62c-ebaa-11e6-9e0d-24f846360265.png)

I think the size of the block label shouldn't be taken into account for the minimum width directive, as it causes strange behaviour and defeats the purpose of this parameter.

**Comment by vivien** [comment]
The *label* property is specific to i3blocks (not i3bar) and was added for convenience to easily add a prefix text to *full_text*. But this causes inconsistencies as the one you described. This property will be deprecated, especially since arbitrary properties are now supported and can be handled directly within the script. So one will want to either include the label from the script, or, adding a static block without *separator* on its left.

**Comment by dikiaap** [comment]
@vivien If use the icon only(I'm using FontAwesome), it doesn't align properly.

![z](https://user-images.githubusercontent.com/8542502/45320115-f0bf5800-b56b-11e8-87d8-019ccf391eef.png)

```
[time-label]
separator_block_width=0
separator=false
full_text=

[time]
command=date '+%a, %d %b %H:%M'
interval=5
```

**Comment by dikiaap** [comment]
Nevermind

**Comment by helge000** [comment]
@vivien, I updated i3blocks just recently and had to do a git bisect to find #61646f2. Mind you, there is a difference between `deprecate` and `remove`.

Please also add migration guides or/and deprecation warnings in the future, not just commit messages.
Thanks,

**Comment by vivien** [comment]
Hi @helge000, you are correct. In the end I considered removing it not a breakage, but I understand that it can bring a frustrating experience. I will restore support for *label* for the next release.

**Comment by helge000** [comment]
@vivien , thanks!
