### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by 123maxmix123** [vivien/i3blocks#221]
Since background option isnt working.
It can be performed only through markup=pango.

Could you add feature in way that before i create the i3block, i can specify its background color, in way that even if i load in that cell an applet like volumeicon, the background of the cell is different from all the bar.

For now what i was able to obtain is:
![screenshot_2017-02-11_17-05-59](https://cloud.githubusercontent.com/assets/17651554/22855212/75c1e8ee-f07c-11e6-8754-702adae641ac.png)

I want to set different background for network manager, and audio manager.
Other output i preformed with markup=pango
While options like, border, background dont work.

**Comment by 123maxmix123** [comment]
Ah sorry, i understood that what i'am asking is to be able to change the color of each background tray icon, which seems to be difficult. But can i change at least global tray background color?

**Comment by kb100** [comment]
i3blocks doesn't handle and cannot influence drawing of the tray, that is done by i3bar. As far as I know, i3bar allows you to change the background color of the entire bar (it appears you have already done that, as the default background is black, whereas yours is grey) but not for just the tray.

**Comment by vivien** [comment]
Indeed, you can change the background of the whole bar via the i3 config, or the background of each individual blocklet through their *background* key (4th line of text with i3blocks master of the via JSON).
