### ISSUE TITLE
Need more clocks

### ISSUE THREAD

**Issue by DeadNumbers** [vivien/i3blocks#223]
I want make 2+ clocks
```
# Date Time
#
[time]
command=env TZ=America/New_York date '+NY %H:%M:%S'
interval=1
separator=true

[time]
command=env TZ=Europe/Moscow date '+MSK %H:%M:%S'
interval=1
separator=true
```
But it's not work. How to do this?

**Comment by 8carlosf** [comment]
If I had to guess, I would say you probably need different block names. try `[time1]` and `[time2]` instead of `[time]` on both

**Comment by tghelew** [comment]
you may wanna try to set the instance to a different name like:
`[time]`
 `command=env TZ=America/New_York date '+NY %H:%M:%s'`
 `interval=1`
 `instance=ny`
 `separator=true`

`[time]`
 `command=env TZ=Europe/Moscow date '+MSK %H:%M:%s'`
 `interval=1`
 `instance=msk`
 `separator=true`

**Comment by vivien** [comment]
Using *instance* is indeed the proper way to interact with i3bar (through i3blocks), because i3bar uses the *name* and *instance* keys to identify a block, e.g. on click.
Note that with latest i3blocks master (or its next release coming soon), you are able to write:
````ini
[time]
instance=ny
TZ=America/New_York
command=date '+NY %H:%M:%s'
interval=1
separator=true

[time]
instance=msk
TZ=Europe/Moscow
command=date '+MSK %H:%M:%s'
interval=1
separator=true
````
