### ISSUE TITLE
human readable intervals

### ISSUE THREAD

**Issue by whoamin** [vivien/i3blocks#224]
Idk how it really works, but I wanna have something else, not only seconds.
```
interval=daily #(in 00:00)
interval=24h
interval=hourly #(in XX:00)
interval=1h
interval=1H #(in XX:00)
interval=30m
interval=30M #(in XX:30)
interval=1h30m
interval=1H30M #(in 1:30, 3:00, 5:30, 7:00, etc)
interval=300m
interval=5S #(every 5 sec, like 01:05, 01:10, 01:15, etc)
```

**Comment by vivien** [comment]
That makes sense. However we'll have to find the right balance to respect convention over configuration. I'd prefer to keep i3blocks "stupid" instead of having user scratching their heads trying to understand the differences between several syntaxes.

**Comment by whoamin** [comment]
In fact, it is configured once and forgotten, so I also do not see the sense of complicating. U can close this.
