### ISSUE TITLE
zerotier bandwidth

### ISSUE THREAD

**Issue by whoamin** [vivien/i3blocks#225]
I'm use zerotier network. I feel the same will be with tun0 (from cjdns)
it's say "zt0 down", but it's not down, it's works and have status UNKNOWN
```
cat /sys/class/net/zt0/operstate
unknown
```
rx_bytes, tx_bytes have a changes

**Comment by vivien** [comment]
Please see the latest revision of the bandwidth script in the [i3blocks-contrib](https://github.com/vivien/i3blocks-contrib/) (or any of its variations), and fill an issue their if they do not work as expected. Thanks!
