### ISSUE TITLE
Escaping &

### ISSUE THREAD

**Issue by ddlr** [vivien/i3blocks#226]
Is there any way to escape the ampersand character? The blocklet appears to be empty if the output of ``command`` contains an ampersand. Example:

```
[blep]
command=echo "test&test"
interval=1
```

Adding backslashes before the & doesn't have any effect.

(version: 1.4-31-ge14ccbd)

**Comment by LordTaifleh** [comment]
your example works for me, showing the & properly. try using `echo -e "test&test"  to enable escaping of backslash characters

**Comment by ddlr** [comment]
I use zsh (but switching to bash doesn't change anything).

Actually, upon looking at the output of the i3blocks command, I realized that this was actually a problem with i3bar (and, as it turned out, Pango). That led me to find i3/i3#1941. Escaping it as ``&amp;`` works.

Honestly, I wouldn't have expected i3 to have this little gotcha when using Pango, which is why I couldn't find it at first; I suppose that would be a lesson for me to not make such assumptions. 😛

Thank you for the help—closing.

**Comment by kb100** [comment]
In pango, `<&>` are special characters and must be escaped. i3blocks should not escape them for you because some blocks actually use pango and hence need these to be treated as special characters.

    def pangoEscape(text):
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

**Comment by ddlr** [comment]
@kb100 Thank you, but I've already figured it out.

**Comment by TitouanT** [comment]
This issue comes from `markup=pango`.
If the block in which you have this issue doesn't need pango then:
+ If you have it set globally you can disable it for that block like this `markup=`.
+ Or remove it from the global settings and only set `markup=pango` when you need it.

If you need pango in this block then you will need to escape special characters like @kb100 said.
