### ISSUE TITLE
ipv6 address switch not working

### ISSUE THREAD

**Issue by JonnyMako** [vivien/i3blocks#227]
I can't figure out how to make i3blocks display by ipv6 addr. The comment in the conf file says:
`# The address can be forced to IPv4 or IPv6 with -4 or -6 switches.`
but how?
like this?
`instance=wlan0 -6`

**Comment by kb100** [comment]
In order to pass arguments to a script, you must you `command=` which is implicit if no arguments are needed.
   
    [iface]
    command=/usr/local/libexec/i3blocks/iface -6
    #instance=wlan0
    color=#00FF00
    interval=10
    separator=false
