### ISSUE TITLE
Add ~/.config/i3blocks/i3blocks.conf to configuration search path

### ISSUE THREAD

**Issue by danijar** [vivien/i3blocks#234]
From [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

It would be very cool to have i3blocks respect this standard so users can have a clean home directory.

**Comment by okraits** [comment]
~/.config/i3blocks/config works here. Or am I missing something?

**Comment by danijar** [comment]
My bad. I did not adapt the filename for the config file.
