### ISSUE TITLE
Volume block mutes master and headphone but only unmutes master

### ISSUE THREAD

**Issue by danijar** [vivien/i3blocks#236]
Right clicking the default volume block mutes both `Master` and `Headphone` channels in AlsaMixer. Right clicking again unmuted `Master` but I have to manually unmute `Headphone`. Is this a problem that can be addressed in the block script?

**Comment by jolange** [comment]
Are you using PulseAudio? I think you get such effects, if you dont specify `-D pulse` to `amixer`. The [volume](https://github.com/vivien/i3blocks/blob/master/scripts/volume#L25-L28) script should determine this on its own, but you could manually test it.

**Comment by danijar** [comment]
But `lsmod | grep pulse` returns nothing but the daemon is running:

```
$ pulseaudio
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
```

**Comment by jolange** [comment]
Does manually running `amixer -D pulse sset Master toggle` properly mute/unmute?

**Comment by danijar** [comment]
Yes, that command toggles correctly while right clicking the volume block does not.

**Comment by jolange** [comment]
@danijar you can either apply the change from #237 or directly set the second parameter of the script to "pulse"

**Comment by danijar** [comment]
@jolange Thanks a lot, that solves the problem for me. On a slightly related note, is there a way to have commands be relative to the install path? To pass the parameter to the volume script, I have to specify it as `command=/usr/local/libexec/i3blocks/volume 5% pulse` but the paths are different on my machines so I can't share the dotfiles.

**Comment by kb100** [comment]
@danijar In your i3 config under that bar section you can put

        status_command SCRIPT_DIR=/usr/local/libexec/i3blocks/ i3blocks

Then in your i3blocks config you can refer to that location like

    command=$SCRIPT_DIR/volume 5% pulse

**Comment by danijar** [comment]
Thanks. And I assume I can set this as a system wide environment variable as well? Because I'd like not just the i3blocks config but also the i3 config to be portable.

**Comment by kb100** [comment]
@danijar yes you could use a system environmental variable as well.
