### ISSUE TITLE
musl - build fails

### ISSUE THREAD

**Issue by E100Beta** [vivien/i3blocks#239]
When building on distributions packaged with [musl libc](https://www.musl-libc.org) only, I get the following error:

    src/sched.c:34:17: error: 'sigset' redeclared as different kind of symbol
     static sigset_t sigset;
                     ^~~~~~
    In file included from src/sched.c:21:0:
    /usr/include/signal.h:231:8: note: previous declaration of 'sigset' was here
     void (*sigset(int, void (*)(int)))(int);
            ^~~~~~
    make: *** [<builtin>: src/sched.o] Error 1
    make: *** Waiting for unfinished jobs....

### Solution
I was able to fix it by just renaming the variable in relevant file (in vim it was `:%s/sigset\([^_]\)/sigset_ng\1/g`). 
I would've proposed a PR, but I feel like my variable name choise is absolutely awful ¯\\\_(ツ)_/¯

**Comment by vivien** [comment]
Thanks for the bug report. I would gladly accept a patch to rename the variable (please include the error snippet in the commit message). For the name, I'd simply use `set`, as used in `block.c`.
