### ISSUE TITLE
cpu: take physical cores/threads into account

### ISSUE THREAD

**Issue by matthiaskrgr** [vivien/i3blocks#240]
I have a dual core sys with 2 physical cores and 2 threads each
/proc/cpuinfo:
````
siblings	: 4
core id		: 0
cpu cores	: 2
````
The i3block widget thingy thinks I have 4 cores so when I run something with 2 threads it says system is under 50% load and not 100% which I think is more appropriate.

I did some quick hacks in the script to make it print 200% in case of 4 threads, but there is probably a better way to handle this globally.
````
$cpu_usage = (100 - $1 )*2; # 100% - %idle
````

**Comment by kb100** [comment]
The point of hyperthreading is to pretend that you have more physical cores than you actually do. Well, more than just pretend. Theoretically, a single hyperthreaded core can run two programs in parallel as long as it has enough registers, and so I don't think in that case we should be calling the load 200%. For your own personal computer, of course, do whatever you please.

**Comment by matthiaskrgr** [comment]
I could try to add a cmdline switch to take number of threads (default) or number of physical cores as baseline for the load calculations.
What do you think?

**Comment by kb100** [comment]
I'de say no, but it's not my repo ;). Ask if @vivien would want to merge something like that.

**Comment by vivien** [comment]
I agree with @kb100. The point of the default scripts is to provide a simple base for the users. If the default CPU script is not quite accurate, this doesn't seem like a big deal.

**Comment by matthiaskrgr** [comment]
Ok, closing...
