### ISSUE TITLE
Date with Calendar (right click)

### ISSUE THREAD

**Issue by ghost** [vivien/i3blocks#248]
For anyone that cares about calendar as me: 

Screen: https://raw.githubusercontent.com/oldgaro/dotfiles/master/Images/Terminalscreen/i3blocks-date-calendar.jpg

https://github.com/oldgaro/dotfiles/blob/master/Distros/i3/i3status/i3blocks/i3-blocks-contrib-master/date

PS: RIGHT-click to access calendar

PS2: Tested on Arch Linux and ubuntu

**Comment by vivien** [comment]
Your jpeg is not available and scripts have all been centralized into the i3blocks-contrib repository. Thank you!
