### ISSUE TITLE
Block executes bash script until case statement is added...

### ISSUE THREAD

**Issue by jrswab** [vivien/i3blocks#249]
This executes just fine in i3blocks:
```
#!/bin/bash
POW=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -o '[0-9]*%' -m 1)
echo $POW
```

This does not execute in i3blocks but does in a terminal:
```
#!/bin/bash
POW=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -o '[0-9]*%' -m 1)
PO=${POW::-1}
 
case $PO in
    [76-100]*)
        tput setaf 2; echo $POW
        tput sgr0
        ;;
    [50-75]*)
        tput setaf 2; echo $POW
        tput sgr0
        ;;
    [26-49]*)
        tput setaf 3; echo $POW
        tput sgr0
        ;;
    [11-25]*)
        tput setaf 3; echo $POW
        tput sgr0
        ;;
    [0-10]*)
        tput setaf 1; echo $POW
        tput sgr0
        ;;
esac
```
I've been searching for what I could be messing up for a day now and can't seem to find the answer.
Any insight will be greatly appreciated!

**Comment by kb100** [comment]
Two ideas: perhaps tput doesn't output to stdout but rather directly to a tty device, or perhaps you need to flush tput output. It looks like you are trying to make a battery script. You may want to use one of the ones already made at https://github.com/vivien/i3blocks-contrib

**Comment by jrswab** [comment]
yes this is a battery script.
I like scripting so I always try to make it myself before just copy/pasting someoneelses code.

After I posted this I did have the thought about tput and will be changing the syntax in the bash script to pango.

**Comment by jrswab** [comment]
replacing tput with
~~~~
'<span foreground="#00FF00">'$POW'</span>'
~~~~
solved my issue. Thanks for you input and help!
