### ISSUE TITLE
i3blocks truncates instance?

### ISSUE THREAD

**Issue by remexre** [vivien/i3blocks#250]
I use UUIDs as mount-paths, so I have a block with `instance=/mnt/60883367-4443-4786-92d5-b551a6d7e872`. However, the associated script dies with (according to `i3blocks -vv`):

```
/mnt/60883367-4443-4786-92d5-b5: No such file or directory
```

Does i3blocks truncate instance names?

**Comment by kb100** [comment]
Instances are truncated to 256 bytes. This has been increased from 32 bytes previously (over a year ago). Updating your i3blocks to the most recent version should solve your issue.

**Comment by remexre** [comment]
Huh, time to bug the Arch maintainers. Thanks!
