### ISSUE TITLE
i3block cpu block stopped working with newer kernel?

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [vivien/i3blocks#251]
it just says , that i cant find any cpu information

    $ /usr/share/i3blocks/cpu_usage 
    Can't find CPU information at /usr/share/i3blocks/cpu_usage line 41.

running the lasted version of debian sid and latests siduction kernel.

```
$ apt-cache policy i3blocks
i3blocks:
  Installed: 1.4-3+b1
  Candidate: 1.4-3+b1
  Version table:
 *** 1.4-3+b1 200
        200 http://ftp.de.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
$ uname -a
Linux x250 4.12.5-towo.1-siduction-amd64 #1 SMP PREEMPT siduction 4.12-7 (2017-08-06) x86_64 GNU/Linux

```

**Comment by jolange** [comment]
What does your `mpstat` output look like?

**Comment by kb100** [comment]
I can confirm this block fails for me too.

    $ mpstat 1 1
    Linux 4.11.0-1-amd64 (redacted) 	08/12/2017 	_x86_64_	(8 CPU)
    
    09:37:35 AM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
    09:37:36 AM  all    4.76    0.00    0.13    0.00    0.00    0.00    0.00    0.00    0.00   95.12
    Average:     all    4.76    0.00    0.13    0.00    0.00    0.00    0.00    0.00    0.00   95.12

**Comment by jolange** [comment]
Strange, the matching used in the script should work for that output. @verfriemelt-dot-org: What makes you think it's a kernel version issue? For me it works with a rather new version:

```
$ mpstat 1 1
Linux 4.12.3-1-ARCH (arch) 	12/08/17 	_x86_64_	(4 CPU)

17:08:13     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
17:08:14     all    2.75    0.00    0.50    0.00    0.00    0.00    0.00    0.00    0.00   96.75
Average:     all    2.75    0.00    0.50    0.00    0.00    0.00    0.00    0.00    0.00   96.75
```

**Comment by verfriemelt-dot-org** [comment]
oh i never tried the command by itself

```
mpstat -V
sysstat version 11.5.7
```

maybe its an issue with the colored output? just guessing, i dont know if there was color before.
i will have a look at the mpstat command a bit more in detail, and report back to you

**Comment by kb100** [comment]
For reference

    $ uname -a
    Linux redeacted 4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux

and 

    $ mpstat -V
    sysstat version 11.5.7
    (C) Sebastien Godard (sysstat <at> orange.fr)

**Comment by kb100** [comment]
Piping the output to vim reveals the likely source of the problem.

    01:51:46 PM  all    0.63^@    0.00^@    0.25^@    0.00^@    0.00^@    0.00^@    0.00^@    0.00^@    0.00^@   99.12^@

`^@` is a null character, which AFAIK does not match `\s`. You know what to do...

**Comment by kb100** [comment]
if (/^.*\s+(\d+\.\d+)[\s\x00]+$/) {   

should fix.

**Comment by verfriemelt-dot-org** [comment]
nice, thats fixed it!

**Comment by Tonus1** [comment]
Ahahah, had same problem and, as I am totally silly with perl, had very long time to find a workaround : 
`$cpu_usage = system ("mpstat | awk \'{ print \$13 }\' | grep -av [[:alpha:]] | grep -a [[:digit:]] | awk \'{ print 100-\$1 }\' ");`

Should have had a look at the repo !

**Comment by vivien** [comment]
I'm closing this hoping it is now fixed in the i3blocks-contrib repo. Thank you!
