### ISSUE TITLE
Clocks/widgets do not update when using full screen

### ISSUE THREAD

**Issue by alephnull** [vivien/i3blocks#255]
A clock is setup as:

```
[time]
command=date '+%d %b %R'
interval=60
```

Stay on a workspace with a full-screen app (I am using fbreader) for a while. Switch back to another workspace with Mod4. 

Notice that the clock has not been updated. Switch to yet another workspace to see the widget update.

**Comment by quinnuendo** [comment]
What do you mean by "for a while"? At least 60 seconds like the interval? Less? Several times 60? 

If you change 60 to less does it become more responsive?

I tried it a bit, there might have been a delay, but it didn't auto update on another workspace switch, but seemed to update on it's own.

**Comment by alephnull** [comment]
> What do you mean by "for a while"? At least 60 seconds like the interval? Less? Several times 60?

Several minutes. To clarify, say the time is 1200 when I switch to the full-screen workspace. After 10 minutes on that workspace, I switch to another workspace, I see the clock widget displaying 1200. I switch to a third workspace and the clock widget displays 1210.

> If you change 60 to less does it become more responsive?

I assume you are referring to `interval`. I set this to 30 but the behaviour was as above. Waiting for a minute on this workspace does finally result in the correct time being displayed.

**Comment by vivien** [comment]
i3blocks must update the status line correctly. You can confirm that by dumping stderr to a file with enough verbosity. If the issue persists, it looks like it's an issue with i3bar. I hardly see what i3blocks is responsible for here. Please feel free to reopen the issue if that persists!

**Comment by LRDPRDX** [comment]
Reproduced this on Ubuntu 16.04 + i3wm.
