### ISSUE TITLE
Is it possible to turn i3bar to red when capslock is on?

### ISSUE THREAD

**Issue by amosbird** [vivien/i3blocks#257]
I'm not sure if this is related to i3blocks though :)

**Comment by kb100** [comment]
https://github.com/vivien/i3blocks-contrib/tree/master/keyindicator

**Comment by amosbird** [comment]
yeah, i'm using that, but the indicators are not attractive. I'd like to turn the whole bar to red.

**Comment by vivien** [comment]
The i3bar protocol does not support bar properties, only block properties, thanks!
