### ISSUE TITLE
battery script stopped showing proper percentage

### ISSUE THREAD

**Issue by stef204** [vivien/i3blocks#258]
the battery script in the "scripts" repo which I have used for ages has stopped working properly and behaves  as such:  as soon as X starts and i3-wm launches, I can see proper number for battery. Once it refreshes, it gets stuck on battery 0% red color.

The 0% is incorrect.  This has just started to happen recently.

```
% acpi -b  
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Discharging, 88%, 02:01:52 remaining
Battery 2: Discharging, 0%, rate information unavailable
```

So it no longer is picking up the right battery (BAT1) and reading BAT0 or BAT2.  Note: I only have 1 single battery (BAT1) in this laptop.

Could be due to changes in kernel or acpi ?

`% uname -sr
Linux 4.13.4`

Note: having similar problems with battery.py from i3blocks-contrib and batterybar (this one shows status for 3 batteries when only 1 is present.)

**Comment by stef204** [comment]
Temp fix, changing this line from
`open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;`
to
`open (ACPI, "acpi -b | grep 'Battery 1' |") or die;`

fixes the issue but probably not ideal.

**Comment by stef204** [comment]
@archvill This could be distro specific, not sure. ACPI state changes on and off, etc.  Ideally, the script would detect the proper battery (or batteries) and state changes dynamically.  "Quick and dirty" fix above OK for now.

**Comment by archvill** [comment]
@stef204 agreed, BTW I'm using Arch.

    Linux io 4.16.9-1-ARCH #1 SMP PREEMPT Thu May 17 02:10:09 UTC 2018 x86_64 GNU/Linux

**Comment by vivien** [comment]
The scripts are now exclusively supported in the [i3blocks-contrib](https://github.com/vivien/i3blocks-contrib), thanks!
