### ISSUE TITLE
Ubuntu package replaces /usr/bin/i3

### ISSUE THREAD

**Issue by tenerhades** [vivien/i3blocks#261]
I've installed i3 from github (Airblader's i3-gaps) and so apt is not aware of it. I installed i3blocks from apt and, when trying to troubleshoot why the config was looking for a different file, I rebooted. The "gaps" command in i3's config stopped working. Closer inspection showed that my /usr/bin/i3 (version 4.14.1 (gaps-next)) had been replaced with /usr/bin/i3 (version 4.13).

Trying to uninstall this version via apt showed me that apt was still unaware of that i3 was installed at all. So my solution was just to replace it by reinstalling i3-gaps according to Airblader's wiki.

Is this an issue specific to the Debian/Ubuntu package? Will my i3 break each time i3blocks gets updated via apt-get upgrade?

**Comment by jpleau** [comment]
This is not really an issue with i3blocks. The package depends on i3 because that's what it is used for.

The quick and easy solution: instead of installing i3-gaps with "make install", do it with "checkinstall", and make sure you name the package as "i3-wm" when it prompts you.

**Comment by tenerhades** [comment]
Actually, it only recommends the i3-wm package, not require. My guess for this is that i3blocks and i3 communicate with the i3bar protocol, instead of an i3-builtin extension language. i3blocks installed a package that it doesn't depend on, and for which is not a metapackage.

Sorry that I've raised this here instead of Ubuntu One (is that the right place?). At least you've seen it.

Also, I just tried what you suggested and got some weird output where it printed the version number followed by a newline about 30 times and told me it wasn't Debian-compliant.

**Comment by jpleau** [comment]
Actually I'm the one who maintains the i3blocks package for Debian and Ubuntu :)

i3blocks depends (recommends) i3-wm because without i3, i3blocks doesn't have much use. It will work without it, but you won't be able to use it for much.

Installing i3-gaps should work with checkinstall though. Do you have output?

**Comment by tenerhades** [comment]
I thought you might be after your username kinda lined up with the maintainer's name.

What you're saying is like saying that dmenu wouldn't be very useful without dwm, but the suckless-tools package doesn't install or overwrite dwm. With good reason: every dwm binary is probably custom. All I did was customize i3, just for the i3blocks package to overwrite it by recommending i3-wm, instead of just suggesting it.

**Comment by jpleau** [comment]
You're going to have this problem with a lot of software in repos though. In case or i3blocks, people who are going to use it will use it with i3 from the repos, hence the recommends.

Following https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-depends I stand by the fact that i3blocks should recommend i3-wm, and not suggest it.

There is a quick and easy solution you can use. What I do (I also customize a lot of things on my systems) is use `equivs`. So make sure you install the `equivs` package first.

Create a control file `i3-wm.equivs` (taken from https://wiki.debian.org/Packaging/HackingDependencies):

```
Package: i3-wm
Version: 99:99
Maintainer: John Doe <john@doe.com>
Architecture: all
Description:  i3-wm dummy package
 dummy i3-wm package
```

Then run `equivs-build i3-wm.equivs`, and install the resulting deb: `dpkg -i i3-wm_99_all.deb`

i3-wm will now be "installed" from this empy dummy package, and you'll be free to do as you please with your customized i3

Hope that helps.
