### ISSUE TITLE
interval=once does not update on first click event

### ISSUE THREAD

**Issue by daanjderuiter** [vivien/i3blocks#267]
All of my blocklets that use $BLOCK_BUTTON have an entry like the following in my i3blocks.conf file, so that they will update as soon as a change occurs, instead of having a 1 second interval:
```
[volume]
command=~/.i3/scripts/volume
interval=once
signal=10
```
The problem is, that when I, for example, change volume (using my scroll wheel) only the second and later scrollsteps leads to a change in the displayed value; the command line output of my volume script will differ from what my bar displays. This is the case for multiple scripts. Reloading i3 leads to a correct value on my bar, until I attemt to change it again.
I have tried inserting a line like `pkill -RTMIN+10 i3blocks` at the end of the script, but this did not change the behaviour, though running it in my shell results in the blocklet changing to the correct value, as expected.

**Comment by kb100** [comment]
Many of these issues are known and have been solved in the contrib repo already. You may want to check out https://github.com/vivien/i3blocks-contrib/tree/master/volume-pulseaudio

**Comment by JShorthouse** [comment]
Move your $BLOCK_BUTTON logic to the start of your script.

I was just typing out a lengthy reply about how I was having the same issue when I realised I was thinking about how these scripts work completely wrong.

The $BLOCK_BUTTON case statement isn't a function that's called separately, it's run with the rest of your block updating code using a variable that's passed to the script. I assume a mouse event just causes a normal update, but with the BLOCK_BUTTON variable set. Therefore if you want the value to update on a mouse event, you obviously need to update the value first, and then run the code to output the new value.

I think what confused me (and probably you too) is the included volume script that for some reason has the case statement at the end. I haven't used it but I assume it must also suffer from the same issue. Perhaps that script should be changed to avoid confusion.
