### ISSUE TITLE
colors and interval=persistent

### ISSUE THREAD

**Issue by shibumi** [vivien/i3blocks#269]
Hello,
I normally set set the colors dynamic. This works totally fine with all intervall modes except `persistent`.

Normally I do something like this:
```
echo -e "$OUTPUT"
echo -e "$COLOR"
```

that way I can colorize my output. This doesn't work with `intervall=persistent`.

**Comment by kb100** [comment]
This is a design choice of how interval=persist works. When you specify a persistent block, you are saying "whenever you get output from me, that is the whole output". The easiest way to get color in persistent blocks is to use pango formatting, as in

    [myblock]
    command=/path/to/mycommand
    interval=persist
    markup=pango

and then in mycommand, use

    echo -e "<span color='$COLOR'>$OUTPUT</span>"

Note the previous line assumes that the output doesn't contain any of the three special pango characters `& < >`. If your output does include any of these characters, you need to escape them. In python this could be implemented as

    def pangoEscape(text):
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

In bash I'm not sure the best way but the following works

    sed 's/\&/\&amp;/g' <<< $TEXT | sed 's/</\&lt;/g' | sed 's/>/\&gt;/g'

**Comment by shibumi** [comment]
thx
