### ISSUE TITLE
[question] Run i3blocks script as sudo

### ISSUE THREAD

**Issue by james64** [vivien/i3blocks#270]
Hey,
  this is not a bug report but a question. I would like to get an advice on how to run packages script in i3blocks as sudo? That is required to get anything from `pacman -Qu`. My script is run with user id 1000 so my guess is that whole i3wm is run with my user as well. How this is done in general?

Only relevant thing I have managed to google up is #155 where `command=sudo pacaur -Qu | wc -l` is used. I tried to set `command=sudo /abs/path/to/my/script`. The result was that I don't see any packages block at all.

Looking further in a meantime. Thanks for your time!

**Comment by james64** [comment]
Is this about adding `/usr/bin/pacman -Qu` into sudoers?

**Comment by vivien** [comment]
Hi, indeed you will have to figure out how to configure your system not to prompt your password when issuing `sudo yourcommand`, that way you can add `command=sudo yourcommand` to i3blocks.

**Comment by james64** [comment]
I added it to visudo file. It works now. Thanks!
