### ISSUE TITLE
crashes and can't be restarted

### ISSUE THREAD

**Issue by matthiaskrgr** [vivien/i3blocks#276]
Hi, I have this very strange issues that when my system generates a lot of disk IO over some time, the journal may get corrupted and/or the systemd service will be restarted.
````
Dec 28 14:34:20 t420 systemd[1]: systemd-journald.service: Watchdog timeout (limit 3min)!
Dec 28 14:34:20 t420 systemd[1]: systemd-journald.service: Killing process 850 (systemd-journal) with signal SIGABRT.
````
This will always cause i3blocks to die and refuse being started again.
There is no trace of it crashing in dmesg or journal log.
i3-msg restart does not revive it, i have to manually log off/close the entire i3 session and log in again in gdm.

Other bars seem so be unaffected, I compiled i3blocks from git;  @ 28c2b092f7d41aa723dad18b0484dca0da1cbbf5

**Comment by vivien** [comment]
Hi @matthiaskrgr! I hardly understand the issue here. Are you able to configure i3 with something like:
````
bar {
    ...
    status_command /path/to/i3blocks -vvv 2>/tmp/i3blocks.err
}
````
and inspect */tmp/i3blocks.err* after reproducing the crash?

**Comment by vivien** [comment]
Feel free to reopen the issue if you get more details.
