### ISSUE TITLE
Can't compile on OpenBSD 6.2

### ISSUE THREAD

**Issue by fedey** [vivien/i3blocks#278]
Hi,

after make clean all or make debug all I get the following errors:

```
# make debug all
*** Parse error in /root/i3blocks: Need an operator in 'PREFIX' (Makefile:3)
*** Parse error: Need an operator in 'endif' (Makefile:5)
*** Parse error: Need an operator in 'SYSCONFDIR' (Makefile:6)
*** Parse error: Missing dependency operator (Makefile:7)
*** Parse error: Need an operator in 'else' (Makefile:9)
*** Parse error: Need an operator in 'endif' (Makefile:11)
*** Parse error: Need an operator in 'endif' (Makefile:12)
*** Parse error: Need an operator in 'DATAROOTDIR' (Makefile:13)
*** Parse error: Need an operator in 'endif' (Makefile:15)
*** Parse error: Need an operator in 'LIBEXECDIR' (Makefile:16)
*** Parse error: Need an operator in 'endif' (Makefile:18)
*** Parse error: Need an operator in 'VERSION' (Makefile:19)
*** Parse error: Missing dependency operator (Makefile:21)
*** Parse error: Need an operator in 'endif' (Makefile:23)
*** Parse error: Need an operator in 'endif' (Makefile:24)
```

I've tried fixing the Makefile by myself by removing unnecessary if statements and I managed to avoid parse errors. Then I get the following errors:

```
# make debug all
make: don't know how to make CPPFLAGS (prerequisite of: debug)
Stop in /root/i3blocks
```

or

```
# make clean all
rm -f src/*.o i3blocks
cc  -o i3blocks
cc: error: no input files
*** Error 1 in /root/i3blocks (Makefile:30 'i3blocks')
```

Here's my version of the Makefile:
https://pastebin.com/vcyGEvP1

**Comment by vivien** [comment]
Unfortunately OpenBSD cannot be supported (yet?) because i3blocks uses realtime signals and event-driven I/O which is not fully supported by this system to my knowledge. I'll think about an alternative implementation for OpenBSD but this has a lower priority for the moment.

**Comment by jolange** [comment]
But this is a pure Make problem, right?

Have you tried using GNU Make?

**Comment by fedey** [comment]
I don't know, I consider myself a noob in the world of BSD and programming ;) As far as I know clang is the default compiler in OpenBSD. How do I force "make" command to use GNU make?

**Comment by jolange** [comment]
It's typically called `gmake` on BSD systems. You probably need to install it first, then use `gmake` instead of `make`.

**Comment by fedey** [comment]
Ok, I'll try that and will let you know. Thanks!

**Comment by fedey** [comment]
I installed gmake - it helped. Thank you!

**Comment by vivien** [comment]
See #127.
