### ISSUE TITLE
i3blocks freezes when clicking clickable blocklet, while having other blocklets with fish scripts as command

### ISSUE THREAD

**Issue by Maxr1998** [vivien/i3blocks#288]
When using e.g. the example blocklet from the README:
```ini
[clickme]
full_text=Click me!
command=echo button=$BLOCK_BUTTON x=$BLOCK_X y=$BLOCK_Y
min_width=button=1 x=1366 y=768
align=left
```

Here's the journal log from right before the click happens.
```
Feb 08 10:12:51 xps13 i3-gnome.desktop[21752]: DEBUG click_parse:65: parsed click: name= instance= button= x= y=
Feb 08 10:12:51 xps13 i3-gnome.desktop[21752]: DEBUG click_parse:65: parsed click: name=button instance= button=button x=1206 y=5
Feb 08 10:12:51 xps13 i3-gnome.desktop[21752]: DEBUG bar_poll_clicked:62: [button] clicked
Feb 08 10:12:51 xps13 i3-gnome.desktop[21752]: DEBUG block_spawn:293: [button] forked child 26077 at 1518081171
```
And then.. it freezes (values don't get updated anymore, e.g. time blocklet stops working.

Here's the full journal after restarting i3:
https://hastebin.com/mewinezoco.vbs

**Comment by jolange** [comment]
Which i3blocks version do you use?

I recently encountered exactly the same issue and found that this was caused by a single block (an own script). If I disable that one, everything is fine. I did not yet figure out what the actual problem is, though.

Could you check if you can verify that a single block is causing this?

**Comment by Maxr1998** [comment]
My version is 1.4.
You're right, when I only have a single, clickable block in my config, it actually works. Trying to find out now which block causes the bug.

**Comment by Maxr1998** [comment]
Ok, it seems it doesn't like my referenced fish scripts in two blocklets. Gonna have to take a look at why this doesn't work.

**Comment by Jab2870** [comment]
I have the same problem but don't have any fish scripts. For me, removing this block solves the problem. Not sure why though.

```
[homeServerUpdates]
interval=300
command=~/.dotfiles/i3/blocks/homeServerUpdates
label=Home Server Updates
```

Here is my shell script

```
#!/usr/bin/sh

count=$(ssh homeServer -t checkupdates 2> /dev/null | wc -l )
if [ "$count" = "0" ]; then
	echo ""
	echo ""
	echo ""
else
	echo $count
	echo $count
	if [ "$count" -gt "5" ]; then
		echo "#FFOOOO"
	else
		echo "#FF8000"
	fi
fi
```

**Comment by Jab2870** [comment]
Added syntax highlighting for shell script

**Comment by Maxr1998** [comment]
Doesn't echo print a newline by default? I think i3blocks can't handle more than one line. Try to use `echo -n` and a normal echo at the end.

**Comment by Jab2870** [comment]
Thanks, unfortunately that didn't work.

FYI, i3 blocks will use the first 3 lines of stdout.

http://vivien.github.io/i3blocks/#COMMAND

> COMMAND
> The value of the command key will be passed and executed as is by a shell.
> 
> The standard output of the command line is used to update the block content. Each non-empty line of the output will overwrite the corresponding property:
> 
> full_text
> short_text
> color
> For example, this script sets the full_text in blue but no short_text:
> 
> echo "Here's my label"
> echo
> echo \#0000FF
> If the command line returns 0 or 33, the block is updated. Otherwise, it is considered a failure and the first line (if any) is still displayed. Note that stderr is ignored. A return code of 33 will set the urgent flag to true.
> 
>

**Comment by Maxr1998** [comment]
Ah, I see. Didn't know that, thanks. Sorry that I couldn't be of any help..

**Comment by vivien** [comment]
Guys do you still have an issue? Especially with latest i3blocks master? I have trouble identifying your issue here. If you still have an issue, are you able to provide me a minimal example so that I can reproduce it? Thank you!

P.S.: @Jab2870 I like the `i3/blocks/foo` path to yours blocklets ;-)

**Comment by Maxr1998** [comment]
@vivien Yes, still happens with `i3blocks-git` that I updated, built, and installed today (thus latest master). An example blocklet that breaks i3blocks in the config from the first post is
```fish
#!/usr/bin/fish
cat /proc/cpuinfo | grep MHz | awk '
BEGIN { a = 0 }
{
    if ($4 > a) {
        a = $4
    }
} 
```
The breaking blocklet itself doesn't have to be clickable, and it's completely irrelevant which block is clicked.
It works perfectly fine when replacing `#!/usr/bin/fish` with `#!/bin/bash`.

What I suspect is that the passed click variables can't be parsed/computed in fish, and the process freezes..

**Comment by vivien** [comment]
This script doesn't print anything. Please provide a working example as well as the corresponding block config. Thank you!

**Comment by Maxr1998** [comment]
Seems to be a different cpu for you. I will post both requested things tomorrow.

**Comment by Jab2870** [comment]
@vivien I am still getting the issue.

My working example is above. I have installed i3blocks-git from the aur. I assume it is the newest version because all of my labels have disappeared. Is this to be expected? I can open a new issue if not.

**Comment by vivien** [comment]
OK I can reproduce the issue. For some reasons, once processes like *fish* or *ssh* are forked, the parent's stdin is messed up, making it blocking again (regardless *O_NONBLOCK*). So i3blocks gets stuck on click processing.

```` ini
command=fish -c date # mess stdin
command=ssh foo date # mess stdin
command=bash -c date # works fine
interval=once
````

I'm investigating this.

**Comment by vivien** [comment]
This problem came from the duplicated standard input shared between the parent (i3blocks) and the child (e.g. `fish -c date`). For some reason that I cannot explain yet, a child process may monopolized the parent standard input (even though the child process exited) and making it blocking again.

To fix this the best practice is to close and reopen a dummy standard input in the child process. The commit  a586a34 does that. Another solution is to close stdin on exec, as commit d376075 does. Both solutions can coexist and are implemented now.
