### ISSUE TITLE
Merge with Anachron/i3blocks?

### ISSUE THREAD

**Issue by Anachron** [vivien/i3blocks#290]
Hey @vivien,

I've created a bigger collection of i3blocks and put them here:
https://github.com/Anachron/i3blocks

Since I am not using i3wm anymore is that possible that you merge them and/or I transfer the repo to you?

If you don't want (no time/bad code quality, etc) it's alright and I'll try to find someone else.

Thank you and have a nice day.

**Comment by vivien** [comment]
Hi Anachron, the proper place for community driven blocklets is the (https://github.com/vivien/i3blocks-contrib)[i3blocks-contrib] repository mainly maintained by @kb100. The requirements to merge scripts in this repo are detailed there. Thank you!
