### ISSUE TITLE
Time display on statusbar

### ISSUE THREAD

**Issue by sirplatypos** [vivien/i3blocks#295]
I am using the time command to display the time on the status bar.  It works relatively well, but for timing reasons, I need it to synchronize with the system clock.  My problem is that at intervals of one second, there is an offset between when the status bar updates, and when the second changes on the clock.  I tried setting the interval to repeat, but that uses 30% of my CPU, and thus is not a viable option.  Is there any other way I can have a time block that actually syncs the status bar updates with the system clock?

**Comment by vivien** [comment]
You want to try using the `persist` interval which assumes the script is run in an infinite loop, and each line triggers an update. Let me know how it goes.
