### ISSUE TITLE
Question: possible to make each block to be control by "tab"

### ISSUE THREAD

**Issue by thyeun** [vivien/i3blocks#297]
Sorry if here is not possible to ask question, instead each block can be using mouse to click to launching certain command, than will it be possible each block can be like - 

an example : when key-binding ```tab + 1 ``` i will know i'm in the position of ```music``` block, than once i know it, i can press enter to launch my command on ```music``` block to call up ```ncmpcpp```

**Comment by vivien** [comment]
Hi! There is no support for keyboard. However you can easily program a mouse click with the *xdotool* command. For instance, I do know that my "time" block is at coordinate `x=1838 y=1066`. I can simulate a click (which triggers the block's command) with:

````
xdotool mousemove 1838 1066 click 1 mousemove restore
````

You can then bind such commands to keys through i3.
