### ISSUE TITLE
unexpected output to bar

### ISSUE THREAD

**Issue by illmath** [vivien/i3blocks#298]
I have a bash script which performs arp-scan on the local network, counts the responses, and prints to stdout, then exits.  On the command line the script works as expected.
when I attempt to add this scrip to my i3blocks configuration file it displays "0" instead of the expected number.

I am able to get standard echo hello world to work, and have other blocks running fine.  
Is this an issue with the time it takes the script to complete?
any advice would be appreciated. I was unable to find any related issues which addressed my problem.
edit1: below is the bash script (i tried setting the uid for the script to root since arp-scan requires it w/ no changes)
`#!/bin/bash
mywifi="MY-SSID"
wifi=$(iw dev wlp58s0 link | grep SSID | cut -d " " -f 2-)
if [[ "$wifi"=="$mywifi" ]]; then
    output=$(sudo arp-scan -l | awk '/([a-f0-9]{2}:){5}[a-f0-9]{2}/&&!seen[$1]++{print $1}' | wc -l)
elif [[ "$wifi"!="$mywifi" ]]; then
    output="u/a"
fi
echo "$output"
exit 0
`
Here is the relevant section from i3blocks.conf
`[devices]
28 label=: 
29 command=~/.i3/devices.sh
30 color=#00FF00 
31 interval=once`

this is a minimal working example that produces the same undesired result
`[devices]
 4 label=devices
 5 command=echo "$(sudo arp-scan -l | wc -l)"
 6 color=#00FF00
 7 interval=once`

**Comment by vivien** [comment]
Can you try again with the master branch of i3blocks?

I tried this from my configuration file:
```` ini
[devices]
label=devices
command=sudo arp-scan -l | wc -l
color=#00FF00
interval=once
````
and I get "devices 11" printed in green.
