### ISSUE TITLE
Set Environment variable for markup

### ISSUE THREAD

**Issue by Jab2870** [vivien/i3blocks#299]
It would be very useful to have access to the markup property inside the scripts.

This would allow us to write things like:

```bash
if [ "$BLOCK_MARKUP" = "pango" ]; then
    echo "<span foreground='green'>Stuff</span>"
else
    echo Stuff
fi
```

**Comment by kb100** [comment]
This is already possible in the next branch of i3blocks. See https://github.com/vivien/i3blocks/issues/279

**Comment by Jab2870** [comment]
Thanks, I'll take a look

**Comment by vivien** [comment]
This is supported in the master branch. Properties are passed as is as environment variables, so the markup property is available through `$markup` in your bash script.
