### ISSUE TITLE
[SOLVED] Custom brightness blocklet not showing up -- Help!

### ISSUE THREAD

**Issue by Lucah97** [vivien/i3blocks#304]
Hey everyone,
I started using i3 last week and had so much nerdy fun customizing it, including i3blocks.
However, the standard blocklet to display brightness doesn't work with my intel backlight, so I wrote a script to get it from a directory in /sys/ and echo it out.

For some reason though, i3blocks does not display this blocklet if I execute my own script on "command=...". Using a different script (like for volume, etc) that I know works with i3blocks, the blocklet does display, so I think it must be my script.

Below is a screenshot of the blocklet, the script and its output. Any help would be appreciated :)
![i3blocks_brightness](https://user-images.githubusercontent.com/12812760/41058477-3761189a-69ca-11e8-9ede-dc7635c7142d.png)

**Comment by kb100** [comment]
It looks like your config should say

    command=~/.customScripts/i3blocksScripts/brightness.sh

not

    command=~/.customScripts/brightness.sh

**Comment by Lucah97** [comment]
Oh my god.... I need more sleep 😂

Thank you, sir!
