### ISSUE TITLE
[Question] Format label spacing

### ISSUE THREAD

**Issue by danbondd** [vivien/i3blocks#307]
Is it possible to format a `label` beyond just the text?

Specifically, there is always a space after the label and I would like to remove it.

For example, if I set: `label=VPN:`, the block will output `VPN: UP`. I would like it to be `VPN:UP`.

**Comment by jeffhuxen** [comment]
I would go into the script directly and look for the print or echo statement and just edit it there (removing the space).

**Comment by vivien** [comment]
I've just pushed support for dynamic properties to the master branch, which means any `key=value` pair written in the block configuration will be passed as an environment variable to the script. This will become the proper way to describe labels to your script. The current *label* property will be deprecated soon.
