### ISSUE TITLE
Pango markup shows in up in bar rather than my custom made font icon made with Glyphter

### ISSUE THREAD

**Issue by danielmunteanu** [vivien/i3blocks#309]
I try to make my own font icons but it seems that I kinda don't know what I am doing .
I tried to make a custom font with Glyphter. I generated my font icon and I tried to use it my i3blocks config but it doesn't renders the icon. It outputs: "<span font_desc="Glyphter">A</span>"

this is my config:

`[icons]`
`command=echo '<span font_desc="Glyphter">A</span>'`
`markup=pango`
`interval=once`

The font is loaded correctly ( it works in libreoffice for example ).

**Comment by vivien** [comment]
I do get a weird big "A" with this example. I'm also using `font pango:Inconsolata, Icons 12` in my i3 config. Please feel free to reopen the issue if it persists.
