### ISSUE TITLE
There's no wiki, I can't find anywhere else a guide for i3blocks.

### ISSUE THREAD

**Issue by vontamar** [vivien/i3blocks#313]
I don't have to guess how to use this software. I've looked into its source code briefly but a wiki is missing and all links to the wiki basically lead to the main page of this repository. If there's no wiki and no guidance anywhere else (not even at Arch wiki) then how do you expect anyone to know how to use it?

Where is the wiki?

**Comment by anselal** [comment]
Please come down. 

The readme file explains how to use i3blocks. 
For customization copy the i3blocks.conf somewhere in your homedir and specify the path of your conf with the '-c' parameter.
For more read the i3blocks.1.md file

**Comment by vivien** [comment]
Hi vontamer! i3blocks is currently being refactored, most documentation will be moved around so I turned off the wiki link. I've put it back, sorry about that! Thanks.
