### ISSUE TITLE
After installing from source, I get the following error: Failed to load bar configuration file

### ISSUE THREAD

**Issue by jaygazula27** [vivien/i3blocks#319]
I'm trying to install and run i3blocks on Fedora 28. Since the package isn't available in the official repo, I decided to try and install it from the source.

I've followed the steps laid out in the readme, namely:

```
git clone https://github.com/vivien/i3blocks
cd i3blocks
./autogen.sh
./configure
make
make install  
```
  
I don't see any errors when I run the above command. However, when I type in `i3blocks` in the terminal, I get the following error:  
```
{"version":1,"click_events":true}
[[]
<0> FATAL bar.c:bar_load:455: Failed to load bar configuration file
,[{"full_text":"Fatal! Failed to load bar configuration file. Increase log level and/or check stderr for details.","short_text":"Fatal! Failed to load bar configuration file","urgent":"true","color":"#FF0000"}
```  
  
According to the readme, it states that the default i3blocks.conf resides in `/etc/`, however I do not see it there. Are we supposed to manually put that in?

I would appreciate any help. Thanks!

**Comment by vivien** [comment]
Hi @jaygazula27!
First please note that i3blocks is being refactored so the master branch document may not be really accurate at the moment. About your issue, well you read it correctly! i3blocks requires a config file.
As first steps for you to have an idea of how i3blocks works, add the following snippet in a `~/.i3blocks.conf` file:
```` ini
[some-text]
full_text=Hello, world!
color=#FF0000

[my-time-block]
command=date +%T
interval=5
color=#0000FF
````

Now run it from your terminal. You should see a continuous output of JSON lines. Now this JSON stream is meant to be read by i3bar, the status bar of i3. To use it, edit your i3 configuration file, and define your *bar* block as follow:

````
bar {
  status_command i3blocks
}
````

Now restart i3 (e.g. with `i3-msg restart`) and your blocks should now appear in the bottom bar of your screen.

For more advance example scripts, you may want to clone [i3blocks-contrib](https://github.com/vivien/i3blocks-contrib) and give its *config.example* file a try.

Hope it helped!
