### ISSUE TITLE
No Scripts in the repo

### ISSUE THREAD

**Issue by Jab2870** [vivien/i3blocks#320]
Hi,

The new version of i3blocks no longer contains the set of default scripts. Are these being moved to a new repo or are you no longer maintaining them?

**Comment by anselal** [comment]
The scripts are now part of https://github.com/vivien/i3blocks-contrib

**Comment by Jab2870** [comment]
My understanding was that that link is for the community contributed scripts. There used to be scripts packaged with i3blocks as well: https://github.com/vivien/i3blocks/tree/1.4/scripts

**Comment by anselal** [comment]
Those are bundled withing the i3blocks-contrib repository !!!

**Comment by vivien** [comment]
Before today we had some official community scripts in i3blocks-contrib and the default scripts bundled with each i3blocks package in i3blocks (in the script repository). That was a bit a PITA to maintain, especially for dependencies which may differ on different plateforms. The idea is now to put every official scripts into i3blocks-contrib, and it will be soon the role of the packager to pick some default scripts to ship with the i3blocks package. Note that the i3blocks-contrib will be one example of a "framework" that i3blocks can run, but that is optional. Power users or picky users may wish to create and maintain their own repository of scripts and run i3blocks on it. Thank you!
