### ISSUE TITLE
broken links in README

### ISSUE THREAD

**Issue by tmccombs** [vivien/i3blocks#325]
the README has several links to pages on http://vivien.github.io/i3blocks which are all broken. It seems like the website for i3blocks is down?

Also https://github.com/vivien/i3blocks/tree/master/scripts no longer exists. Is the plan that all blocklets will be in the contrib repo now?

**Comment by vivien** [comment]
You are totally correct! The master branch is in rework, scripts have been
moved to the contrib repository and the documentation will be completely
reworked soon. Thank you!
Le mar. 18 sept. 2018 à 02:31, Thayne McCombs <notifications@github.com> a
écrit :
