### ISSUE TITLE
Bandwidth-scripts fails when using 3g/LTE

### ISSUE THREAD

**Issue by davralin** [vivien/i3blocks#326]
[bandwidth} fails when connected via 3g/LTE.
Reason:
`/sys/class/net/wwp0s20f0u6i12$ cat operstate`
`unknown`
It's up though, I see rx/tx-bytes go up.

`/sys/class/net/wwp0s20f0u6i12$ cat uevent`
`DEVTYPE=wwan`
Could perhaps be used for a check instead, or if the operstate-check fails.

**Comment by vivien** [comment]
Hi! Default scripts have been moved to the contrib repository. I think this is already raised at https://github.com/vivien/i3blocks-contrib/issues/174. Thank you!
