### ISSUE TITLE
Cannot use environment variables

### ISSUE THREAD

**Issue by LuisMichaelis** [vivien/i3blocks#328]
Hi.
I'm new to i3blocks and my configuration file seems to be incorrect.
This is it:

```
[volume]
command=/home/lmichaelis/Scripts/i3-volume
label=VOL
interval=once
signal=10

# Query my default IP address only on startup
[ip]
command=hostname --ip-addresses | awk '{ print "IP:" $1 }'
interval=once
color=#91E78B

# Update time every 5 seconds
[time]
command=date +%T
interval=1

[wifi]
command=/home/lmichaelis/Scripts/i3-wifi
label=WIFI
INTERFACE=wlp0s29f7u5
interval=60
```

The section that is causing problems is the last one 'wifi'. When I start i3blocks it says:
```
ERROR parse_bar:162: malformated line: INTERFACE=wlp0s29f7u5
ERROR main:70: Try 'i3blocks -h' for more information.
```

and I don't get why. The section is copied from https://github.com/vivien/i3blocks-contrib/tree/master/wifi and what it should be doing is set the environment variable 'INTERFACE'.
This issue appears in every block I try to set environment variables in.
I am using i3blocks version 1.4.

**Comment by vivien** [comment]
Hi @LuisMichaelis!
Dynamic properties are a new feature implemented in the master branch, it has not been released yet. Thus i3blocks 1.4 fails on unknown keys.

**Comment by LuisMichaelis** [comment]
I've got it from the official arch repositories and because this is apparently used everywhere I just assumed that it is in the latest version. I have seen that the latest release is over 3 years old but the blocklets in the official i3blocks-contrib repository are using this feature. Why is that?

**Comment by vivien** [comment]
master branches of i3blocks and i3blocks-contrib are work in progress by definition. The last version of i3blocks is indeed 3 years old, and new features have been implemented a few weeks ago. This will be released soon. In the meantime, you can install i3blocks-git from AUR if you want to try master. I'm closing the issue. Feel free to comment still.

**Comment by LuisMichaelis** [comment]
Okay then. Thank you for answering :)

**Comment by lensz** [comment]
Just wanted to leave a comment, that I just ran into the same problem. Fixed it by building i3blocks from source.

I know there is nothing wrong with the current situation, but maybe adding a short line to the README of i3blocks-contrib that most of the blocks require i3blocks >1.4 wouldn't hurt either. :)

**Comment by kb100** [comment]
@lensz I've updated the statement in the readme to make it clearer that the latest release of i3blocks is not new enough and that the git version must be used.

**Comment by lensz** [comment]
> @lensz I've updated the statement in the readme to make it clearer that the latest release of i3blocks is not new enough and that the git version must be used.

cool, will you create a pull request for that?

**Comment by kb100** [comment]
@lensz Oops I forgot to push. It's updated now (no PR because I am the maintainer).
