### ISSUE TITLE
Only run command on click

### ISSUE THREAD

**Issue by benkaiser** [vivien/i3blocks#33]
I am migrating from py3status to i3blocks due to the fact that it looks simpler and cleaner, however one nice feature I had in py3status was an item that could be clicked and a command run.

This can almost be implemented by a command and no signal / interval and full_text for the title, however one issue I have is that it runs on load. Is there a way to set up a button that would not be executed until a mouse click has been fired?

**Comment by acron0** [comment]
What about when you want to generate text using `command` *and* have a response to click?

**Comment by rileyrg** [comment]
Any further on this? I want to click my i3blocks volume status to bring up pavucontrol

**Comment by Rizwan-9000** [comment]
> Any further on this? I want to click my i3blocks volume status to bring up pavucontrol

Same Here 😅
I want i3blocks to be responsive - that will be amazing like cherry on top!

**Comment by q1zhen** [comment]
```python
if __name__ == "__main__":
	clicked = os.getenv("BLOCK_BUTTON")
	if clicked: os.system("xdg-open https://google.com")
	else: main()
```

This is how I am handling it: detect from the environment, and if `BLOCK_BUTTON` exists (not empty string), then it is a click event.
