### ISSUE TITLE
Standard Templates for Issues 

### ISSUE THREAD

**Issue by h3ct0rjs** [vivien/i3blocks#330]
Hi @vivien

After checking this awesome repo I was wondering if you would like to implement something more standard when we're opening an issue, I was thinking in [github issue templates](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/), I need to do a couple of pull request for my goal of hacktoberfest.

Please let me know what things you would like to ask when people is opening an issue :smile: :grinning:

**Comment by kb100** [comment]
I would like to note that almost all issues people have with i3blocks are on the blocks/scripts side (now contained in i3blocks-contrib) and not the scheduler side (the i3blocks repo), so I'm not sure if problems with i3blocks itself are standard enough to to be templatable. The i3blocks-contrib repo does have an issue template though.

**Comment by h3ct0rjs** [comment]
@kb100 hmm I would like to check that. I think that this could be a great option in the contrib side.

**Comment by vivien** [comment]
Hi @h3ct0rjs! Indeed the core repository does not need an issue template at the moment in my opinion, but i3blocks-contrib does and actually has a [CONTRIBUTING.md](https://github.com/vivien/i3blocks-contrib/blob/master/CONTRIBUTING.md) and [ISSUE_TEMPLATE.md](https://github.com/vivien/i3blocks-contrib/blob/master/ISSUE_TEMPLATE.md), as @kb100 mentioned. Have fun hacktoberfesting! ;-)

**Comment by h3ct0rjs** [comment]
Thanks, I also develop  a quick block for enable or disable the touchpad in my laptop, it could be a good option.
