### ISSUE TITLE
Scheduled commands and i3bar hide mode.

### ISSUE THREAD

**Issue by dhanjit** [vivien/i3blocks#332]
In i3 config:

```
bar {
        mode hide
}
```

Now when I press mod key, the bar shows itself. But the execution of a i3block command (say scheduled every hour) will also start.

Is there a way to stop the block from executing outside of scheduled interval?

**Comment by vivien** [comment]
If I understand your problem correctly, I cannot reproduce it. I've configured a bar like this:

````
bar {
  mode hide
  status_command i3blocks
}
````

and I have configured a blocklet like this:

```` ini
[counter]
label=Counter:
_count=0
command=printf '{"full_text":"%s", "_count":%d}\n' $_count $((_count + 1))
format=json
interval=10
````

(note that I'm using latest i3blocks master with support for dynamic properties.)

After restarting i3, I can show and hide the bar with the mod key but this block still shows 0 for the first 10 seconds, then 1 and so on, as expected. If the block was scheduled every time I press mod (as I understood), the counter would be incremented right away, which is not the case.

Did I miss something in your description?

**Comment by dhanjit** [comment]
Hi @vivien I stand corrected.

It works as intended.

```

[counter]
label=Counter:
command=printf '{"full_text":"%s"}\n' "$(date)"
format=json
interval=100
```

I checked with the stable release from arch package too. It works as intended. No refresh happens just because of bar show event.

I will close the issue.  I was misled by some awry script of mine it seems. That said, when is the next stable release out?

**Comment by vivien** [comment]
Good! I must be able to release a new version in a few days hopefully.
