### ISSUE TITLE
No action on blocklet click

### ISSUE THREAD

**Issue by maxpowers-zz** [vivien/i3blocks#335]
When clicking a blocklet no action is executed anymore.

I tested this behavior with the minimal config listed below.
The label doesn't change on clicking the blocklet.

#### i3 -v 
    i3 version 4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors

#### i3blocks version
    aur/i3blocks-git 1.4.r62.ga44b67f-1 (+13 0.01%) (Installed: 1.4.r110.g317c145-1)
    Define blocks for your i3bar status line

#### ~/.config/i3blocks/config 
    [click]  
    full_text=Click me!
    command=echo "Got clicked with button $button"  
    color=#F79494  

#### i3blocks call in ~./config/i3/config  
    status_command 2>/tmp/i3blocks.err i3blocks -vvv | tee /tmp/i3blocks.out

#### i3blocks.err output on blocklet click
    <3> TRACE sched.c:sched_start:282: received signal 29 (I/O possible), file descriptor 0  
    <2> DEBUG line.c:line_parse:65: &0:000: [  
    <2> DEBUG line.c:line_parse:65: &0:000: {"name":"click","button":1,"modifiers":[],"x":1181,"y":13,"relative_x":0,"relative_y":13,"width":72,"height":23}

**Comment by mna** [comment]
Same for me, it stopped working recently, though `i3-gaps` was recently updated (2018-11-04 on Arch), maybe something conflicts with i3blocks in that new version?

**Comment by kb100** [comment]
Same, clicks broken.

**Comment by mna** [comment]
I was notified that the commit that causes the issue is from the upstream `i3` project, so I opened the issue there: https://github.com/i3/i3/issues/3522

**Comment by Maxr1998** [comment]
I downgraded to i3-wm 4.15, and it works again, so definitely an issue with the recent i3 update..

**Comment by orestisf1993** [comment]
It's definitely caused by the commit you mentioned but the problem appears
because i3blocks doesn't handle correctly the JSON array.

**Comment by kb100** [comment]
For a longer term solution, perhaps we should depend on an external library like json-c instead of rolling our own json parser?

**Comment by gportay** [comment]
@kb100: I think relying on an external json library is not relevant as long as the protocol does not send complex structures such as nested objects or arrays. The current implementation is simple enough and match the current needs.

@maxr1998: I saw your patch too late. Our fix is quite similar.

I think I will implement the modifiers later to pass it as a white space separated string.
