### ISSUE TITLE
Icons and text suddenly colorless

### ISSUE THREAD

**Issue by zaknafein99** [vivien/i3blocks#336]
I don't know if this is an issue or something broke, after dabbling with fontconfig my i3blocks suddenly got with text and icons in a grey color, they work, but all color is gone

Screenshot:
https://imgur.com/a/q72OS23

**Comment by vivien** [comment]
I have absolutely no idea. Let us know if you fixed this fontconfig issue!

**Comment by vivien** [comment]
Closing this for lack of information. Feel free to reopen if necessary.
