### ISSUE TITLE
Scripts criteria

### ISSUE THREAD

**Issue by vivien** [vivien/i3blocks#36]
This issue is meant to describe the behavior of the default status line and the acceptance criteria for scripts.

A script has good chances to be part of the default [scripts](https://github.com/vivien/i3blocks/tree/master/scripts) if:
- It has no external dependency (or a well justified one).
- It is transparent: e.g. if the machine has no battery or wireless connection (think desktop), the corresponding block should not be displayed.
- It works on any distribution (e.g. ip/ifconfig's output may differs between different versions).
- It uses no fancy unicode chars (the default font may certainly not like it).

A useful and well-written script is a good candidate for the [contrib](https://github.com/vivien/i3blocks/tree/master/contrib) folder, if:
- It doesn't answer the previous points.
- It is too much specific (e.g. a specific music player, location or service).

Otherwise, any example is welcome in the [wiki](https://github.com/vivien/i3blocks/wiki).

**Comment by vivien** [comment]
As suggested on Gitter, I'm about to unify the contrib scripts and the default scripts and comment them out in the default config. If any of you objects to this union, speak now or forever hold your peace.

**Comment by Nycroth** [comment]
That's all cool with me.

**Comment by vivien** [comment]
The default scripts are now merged into the i3blocks-contrib repository.
