### ISSUE TITLE
Question: using custom separator with hidden blocks

### ISSUE THREAD

**Issue by anlar** [vivien/i3blocks#361]
Hi,
I wanted to create configuration for status bar that have separators not only between blocks but also at the end of the last block. As by default i3bar drawing them only between blocks I've used custom separator from i3blocks FAQ. Problem is that I have some blocks that may be hidden (their script will return empty `full_text`) but with custom separator they are always visible. E.g that config will not display empty block.

```
[empty_block]
label=L
command=echo ''
interval=30
```
But second one will always display `L 〉`
```
full_text=〉
align=center
color=#666666
separator=false
separator_block_width=7

[empty_block]
label=L
command=echo ''
interval=30
```
Is there any workaround to make custom separators work with empty blocks?

**Comment by anlar** [comment]
> I believe that i3bar already supports a custom separator symbol. Does this not accomplish what you want?
It is. But it will only draw it between blocks and I need it after the last block too.

**Comment by vivien** [comment]
What about specifying a custom *separator_symbol* to i3bar and add
static blocks with that separator only at the beginning and end of
your config?

Something like the following:

````
bar {
  separator_symbol ":|:"
  status_command i3blocks
}
````

and:
````
[sep]
full_text=:|:
separator=false

[block1]
full_text=block 1

[block2]
full_text=block 2

[block3]
full_text=block 3
separator=false

[sep]
full_text=:|:
separator=false
````

(Note the `separator=false` for block3 as well.)

You'll still have to play with the color and width, but I hope it
gives you an hint.

**Comment by anlar** [comment]
@vivien , thanks, it's worked. For the reference, blocks config:

```
[last_block]
full_text=block 3
separator=false
# default separator_block_width is 9 and you need half of that to make it look properly here
separator_block_width=4

[separator_at_the_end]
full_text=:|:
# color from colors.separator
color=#ff0000
separator=false
```
