### ISSUE TITLE
Unable to obtain BLOCK_BUTTON in python blocklet

### ISSUE THREAD

**Issue by omrihar** [vivien/i3blocks#365]
Hello,

I've been trying to create a blocklet using a python script. The blocklet is supposed to indicate whether my bluetooth headphones are connected, and if not, create a button that tries to connect to them. I manage to pass the mac address of the headphones using `BLOCK_INSTANCE` without a problem, but I am unable to get the `BLOCK_BUTTON` environment variables to be set. I've tried using `notify-send` to get notifications whenever it is set, or saving a line to a file with all environment variables on script call, but all never managed to get a `BLOCK_BUTTON` environment variable. 

I find it strange since I do see it set for bash scripts, and I do get the `BLOCK_INSTANCE` environment variable in the python script, so I don't think it's about passing variables from i3blocks to the script. 
A bare bone example of my script is given here:

```python
#!/usr/bin/env python
import subprocess
import os

mac = os.getenv("BLOCK_INSTANCE")
sp = subprocess.getoutput(f"bt-device -i {mac} | grep Connected")
button = os.getenv("BLOCK_BUTTON", "Nope")

if button is not '':
    subprocess.call(["notify-send", f"button {button} clicked"])
    print(button)
    os.sys.exit(0)

if sp[-1] == "1":
    print("")
else:
    print("Connect")
```

The indicator or Connect strings are displayed properly, it's only the click events that I'm missing. Any help in debugging would be very appreciated!

**Comment by omrihar** [comment]
OK, I've found the cause of the problem, but I'm not sure if it's not a bug, so I'll leave it open. When I passed the instance variable in the i3blocks.config file, I put the mac address value in quotes (i.e. instance="mac:address:...").
This caused the i3blocks not to trigger the mouse click events. Once I removed the quotes everything seems to work.

**Comment by kb100** [comment]
i3blocks copies everything to the right of the `=` sign exactly, so in your example if you put `instance="mac:address:..."` then the value of `mac` in your script will be `"mac:address:..."` including the quotes, this could be causing your bt-device script to error making your script crash. You can try diagnosing these things by running the script from the command line.

**Comment by vivien** [comment]
Hi @omrihar, thanks for the report. I do see where i3blocks can be improved here. However regarding this issue, the proper fix is to not quote the *instance* value, as @kb100 explained. I'm closing this, thanks!

**Comment by omrihar** [comment]
Thanks both @kb100 and @vivien. I don't think the script itself is crashing, since it runs to the end and produces the correct output (earphone symbol or Connect string), but rather something in i3blocks fails, since the result is just that the `BLOCK_BUTTON` environment variable is not set. However, indeed, not quoting instance solves my problem so I'm happy with closing the issue.

**Comment by vivien** [comment]
Yeah, on click i3bar passes the *name* and *instance* of the concerned block as JSON string. i3blocks unquotes strings from JSON, but not from INI, hence it is looking for a block with an *instance* being `mac:address:...` instead of `"mac:address:..."`...
