### ISSUE TITLE
Issue in the docs

### ISSUE THREAD

**Issue by padomu** [vivien/i3blocks#367]
Hi, in the section "Blocks" you write:

> In this example, block2 contains a foo property equal to "bar" and a quux property equal to " quuz" (including the leading space).

So I might not get it but isn't that wrong? Block2 seems to only contain quux=quuz but not foo=bar.

**Comment by Jomik** [comment]
At the top of the code snippet right above that paragraph:
```
# Properties not preceded by a section are considered global
# and merged into every section declarations.
foo=bar
```

**Comment by vivien** [comment]
As @Jomik correctly mentioned, *block2* will contain a property `foo=bar`. Feel free to reopen the issue if it isn't clear yet.
