### ISSUE TITLE
With format=json $button does not contain just the button number but a whole json array of the block

### ISSUE THREAD

**Issue by Ingvix** [vivien/i3blocks#370]
I was wondering why my click function never made any change but after redirecting the output to a file I realized what the title states.
This is the output of echoing `Click amount: $_count $button`:

> Click amount: 1 {"":"","command":"/home/ingvix/bin/$BLOCK_NAME","markup":"none","color":"#9ab0c9","border_top":0,"border_right":0,"border_left":0,"border_bottom":2,"border":"#ffffff","separator":false,"name":"click-loop","full_text":"Click me!","interval":"persist","_count":0,"format":"json","button":1,"modifiers":[],"x":431,"y":12,"relative_x":37,"relative_y":12,"width":69,"height":22}

**Comment by vivien** [comment]
Can you show me you blocklet config as well as the output you expect?

**Comment by Ingvix** [comment]
Here's the test blocklet:
```
[click-loop]
full_text=Click me!
command=/home/ingvix/Scripts/$BLOCK_NAME
interval=persist
_count=0
format=json
```
Here's the script:
```
#!/bin/bash

while :; do
    while read -t 5 button; do
        _count=$((_count + 1))
         echo "Click amount: $_count $button" > /home/ingvix/click.txt
    done
    _count=0
    #echo "Click me!"
done
```
What I expect after I click the blocklet for the first time with the left mouse button is this:

> Click amount: 1 1

in the click.txt file. It only outputs that if I comment out the formatting to json. Otherwise it gives me what's stated in the start comment. 

Is this how it's actually suppose to work and I have just misunderstood it? I thought the json formatting would only affect how the output of the command is handled and not the format of variables fed to the command.

**Comment by vivien** [comment]
Hi @Ingvix. The described behavior is correct. As explained in the [click](https://vivien.github.io/i3blocks/#_click) section of the readme, clicking a persistent block will write all variables as JSON to the command's stdin. Either don't use the json format if you want the standard input to only receive the button value, or do not use a persistent block so that all variables get injected in the environment. I'm closing the issue. Feel free to reopen if I missed anything. Thank you!

**Comment by Ingvix** [comment]
I see, so if I need to use persistent block with json and get the button used, I need to parse the value from json string. It just seemed strange that the other variables seemed to behave normally compared to $button but now I see the logic here. The others aren't updated and use the initial values for the script too unless I grab the new values from the incoming $button string. Thanks.

**Comment by vivien** [comment]
Yes you get this right. Once the persistent block is running, stdin is used to pass variables. Since the block outputs JSON, I'm assuming you can read JSON too, and may need data other data only the button value (click positions, modifiers, custom variables, etc.)
