### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [vivien/i3blocks#372]
I would like to point out that identifiers like “[`_BAR_H`](https://github.com/vivien/i3blocks/blob/575159264f2d0cbd4fb86ac4e921b3850ddf3bc2/bar.h#L19 "Update candidate")” and “[`_JSON_H`](https://github.com/vivien/i3blocks/blob/8d89804fa556a66a4a215fd792ddbc3333d0afc6/json.h#L19 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by vivien** [comment]
Please feel free to submit a PR removing the leading underscores in the various include guards of the project.

**Comment by vivien** [comment]
I'm closing this as it doesn't cause any issue to i3blocks. I would gladly accept a patch renaming the include guards if that is causing any harm.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by vivien** [comment]
Are you willing to submit a patch renaming the include guards or are you simply peeling off the C standard? ;-)
