### ISSUE TITLE
Zombie Processes appear after block clicking

### ISSUE THREAD

**Issue by danto7** [vivien/i3blocks#373]
Hello,
I have some blocks doing things in the background. 
For example a volume block which opens pavucontrol on click.
For some reason it does it only the first time after that the block doesn't exit and remain in Zombie Status.
For me it looks like i3blocks doesn't get the SIGCHLD signal and doesn't clean up. (Attention noob speaking)

I tried a few things out like switching the language (to ruby), but I can't figure it out.
I hope somebody here can help me.

Best Regards

i3block config (snippet):
```ini
# Global properties
command=$HOME/.config/i3blocks/blocks/$BLOCK_NAME $BLOCK_BUTTON
separator_block_width=10
markup=none

[volume]
interval=once
signal=10
```

status command:
```bash
#!/bin/bash
if [ "$1" -eq "1" ]; then
  i3-msg -q exec pavucontrol
fi

volume=$(pamixer --get-volume | tr -d '[:space:]')
isMuted=$(pamixer --get-mute | tr -d '[:space:]')

if [ "$volume" -eq 0 ] || [ "$isMuted" = "true" ]; then
  icon="🔇"
elif [ "$volume" -lt 30 ]; then
  icon="🔈"
elif [ "$volume" -lt 80 ]; then
  icon="🔉"
else
  icon="🔊"
fi

echo "$icon $volume%"
```

i3blocks err log:
```
DEBUG sched_start:177: received signal 29 (I/O possible)
DEBUG click_parse:65: parsed click: name= instance= button= x= y=
DEBUG click_parse:65: parsed click: name=volume instance= button=1 x=2206 y=12
DEBUG bar_poll_clicked:62: [volume] clicked
DEBUG block_spawn:293: [volume] forked child 8768 at 1555315321
DEBUG click_parse:65: parsed click: name=volume instance= button=1 x=2200 y=15
DEBUG bar_poll_clicked:62: [volume] clicked
DEBUG block_spawn:244: [volume] process already spawned
DEBUG click_parse:65: parsed click: name=volume instance= button=1 x=2200 y=15
DEBUG bar_poll_clicked:62: [volume] clicked
DEBUG block_spawn:244: [volume] process already spawned
DEBUG click_parse:65: parsed click: name=volume instance= button=1 x=2200 y=15
DEBUG bar_poll_clicked:62: [volume] clicked
DEBUG block_spawn:244: [volume] process already spawned
```
shell output ps -ax | rg <pid>:
```
~
🍕 ps -ax | rg 8768
 8768 ?        Z      0:00 [bash] <defunct>
 9066 pts/2    S+     0:00 rg 8768
```

**Comment by kb100** [comment]
i3blocks does not handle "cleaning up" after a process is spawned with i3-msg exec, so the most likely thing seems to be that this is an issue with pavucontrol. Sorry I can't be much help. This could be a very subtle bug in a number of different places and I don't know where to start. If there is any other debug info you can provide feel free to add more and I'll look again.

**Comment by vivien** [comment]
Hi @danto7,
I did experience a few zombies process as well, this should not happen. I'll make a few tests and get back to you.

**Comment by danto7** [comment]
@kb100 Thanks for the fast response.
I have tested the same thing with nm-connection-editor: same result
So probably has nothing todo with pavucontrol.
@vivien Thanks :)

**Comment by kb100** [comment]
@danto7, can you get a zombie process just using i3-msg exec from the command line? Or does it only happen when the process is spawned from i3blocks?

**Comment by danto7** [comment]
This does only happen when the process gets spawned by i3blocks.
When I execute i3-msg exec pavucontrol or my bash script directly from the shell everything works fine.

**Comment by vivien** [comment]
Hi @danto7, do you still get zombies with latest master? Since 56844da i3blocks now errors out in such case, but reap them anyway. Feel free to reopen the issue if you ever get this "unknown child process X" error. Thanks!

**Comment by lidgnulinux** [comment]
Hello, I make a toggle menu script (launch and kill xfce4-appfinder) and it works on other place exec i3blocks : 
```
#!/usr/bin/bash

if pgrep -x "xfce4-appfinder" > /dev/null; then
        killall xfce4-appfinder
else
        xfce4-appfinder
fi
```
Expected : 
When I click the block I made, xfce4-appfinder will launch, and when I click again, xfce4-appfinder will be terminated.

What happen : 
When I click the block I made, xfce4-appfinder will launch, and when I click again, xfce4-appfinder still opened and not terminated.

Any clue ? Thanks.
