### ISSUE TITLE
A new release is needed!

### ISSUE THREAD

**Issue by alindt** [vivien/i3blocks#374]
**Reading https://vivien.github.io/i3blocks/#_blocks...**
 
`==============================================`
\# Properties not preceded by a section are considered global
\# and merged into every section declarations.
foo=bar

[block1]
baz=qux

\# This is a comment
[block2]
quux= quuz

In this example, block2 contains a foo property equal to "bar" and a quux property equal to " quuz" (including the leading space). Everything after the equal sign will be part of the value, thus inline comments won’t be stripped out.

At runtime, these properties are simply variables, that are passed along to the status bar program when printing is necessary. However on startup, i3blocks checks some optional properties to eventually setup the scheduling of a command.

If a block specifies a command, then all of its properties are passed as environment variables at execution, which means that the foo=bar property will be available from a shell script with $foo. The output of the command is used to update the values of these variables. The values are reset to default (as defined in the configuration file) before the update, so that blocks get a consistent behavior at each execution.
`==============================================`

**I'm left to believe custom `foo=bar` properties in a block will be passed as environment variables to the block program, but...**

```
command=~/.config/i3blocks/scripts/$BLOCK_NAME
separator_block_width=15
markup=none

[my_block]
markup=pango
interval=1
foo=bar
```
**...yields...**
```
DEBUG parse_bar:145: [my_block] new block
ERROR parse_property:98: unknown key: "foo"
ERROR main:70: Try 'i3blocks -h' for more information.
```

**Am I missing something obvious or does the description page need an update?**

**Comment by alindt** [comment]
This seems to be fixed in 1169da6.
There have been **many** commits to master since the last release (v1.4 = 37a7749), I think a new release is really overdue!

**Comment by tbodt** [comment]
@vivien

**Comment by gportay** [comment]
As far as I know, the release is upcoming, but there is still some cleanup to be done first. I would like to write some tests for integration.

**Comment by panaman67** [comment]
@gportay @vivien bump?

**Comment by panaman67** [comment]
With 1.5, will there be a tagged release to accompany it?

**Comment by vivien** [comment]
I am closing this since I've just pushed a tagged (and signed) 1.5 release ;-)
