### ISSUE TITLE
bandwidth script always show wireguard interfaces as down

### ISSUE THREAD

**Issue by CryptKid** [vivien/i3blocks#377]
The bandwith script always shows wireguard VPN interfaces as "down", because it Queries /sys/class/net/$INTERFACE/operstate = up and wireguard sets it to "unknown" when up (because it does not check if the tunnel works, i guess)
An ugly fix could be to exclude "wg*" from operstate=up
A better solution could be to run "nmcli device show $INTERFACE" and check GENERAL.TYPE

I could create a PR to implement this, if you want

**Comment by vivien** [comment]
Please refer to the i3blocks-contrib repository, thank you!
