### ISSUE TITLE
Using pipes in block `command`

### ISSUE THREAD

**Issue by vikdotdev** [vivien/i3blocks#378]
I've ran into issue while trying to pipe output of a watch command/daemon of [xkb-switch](https://github.com/ierton/xkb-switch).

To put it other words, `xkb-switch -W` works just like `ping` command.
Here's my block:
```
[kblayout]
command=bash -c 'xkb-switch;xkb-switch -W' 
# or just `command=xkb-switch -W`, first part is for initial layout display
interval=persist
```

I'd like to make it's output uppercase, `xkb-switch -W | tr a-z A-Z`. This works as expected in the command line but when I try to use it as a `command` in i3blocks it doesn't work. It just won't update.

Is it possible to use pipes in block command? Any other way can I achieve immediate feedback on layout change?

**Comment by zsugabubus** [comment]
Try `xkb-switch -W | stdbuf -oL tr a-z A-Z`.

**Comment by vikdotdev** [comment]
Works like a charm! Prepended that with non-watch command to get the initial value `xkb-switch | tr a-z A-Z;xkb-switch -W | stdbuf -oL tr a-z A-Z` and it works great. You have my gratitude, sir.
