### ISSUE TITLE
padding after text

### ISSUE THREAD

**Issue by andersfylling** [vivien/i3blocks#379]
To this block, is it possible to add some padding/margin on the right side of the text?
```
[keyindicator]
instance=NUM
interval=once
signal=11
```

Essentially: "NUM" => "NUM "

**Comment by albocc** [comment]
If your instance name is also the label text, you could change the label to have a space at the end, e.g.:

```
[keyindicator]
label=NUM 
instance=NUM
interval=once
signal=11
```

**Comment by vivien** [comment]
It looks like this issue if fixed. Otherwise, please refer to the i3blocks-contrib repository. Thanks!
