### ISSUE TITLE
Alternative `min_width` when in "short mode"

### ISSUE THREAD

**Issue by albocc** [vivien/i3blocks#381]
It's great that the status bar can collapse to a "short mode" when space is limited. And I also appreciate the `min_width` option for blocks that change in length often, like for example fan RPM etc.

However, they don't seem to work well together, because when "short mode" is activated, `min_width` is still applied and leaves useless gaps now, since the displayed text is much shorter. The best solution in my opinion would be an alternative `min_width_short` that is used when displaying the block's `short_text`. 

### Example

![Display with long_text](https://i.imgur.com/4JBlIbZ.png)
![Display with short_text](https://i.imgur.com/cezhfAx.png)

As you can see, both variants are the same size, so the "short mode" cannot be taken advantage of.

**Comment by vivien** [comment]
Hi @albocc. I understand your issue, however that is not related to i3blocks. i3blocks only prints out the key you gave so that the upper layer (i3bar) can interpret it. You may want to discuss with within the i3 repository or @Airblader's i3-gaps, thanks!
