### ISSUE TITLE
Update Ubuntu package

### ISSUE THREAD

**Issue by artslob** [vivien/i3blocks#383]
In this issue I ask for package update in Ubuntu repository.

As it seems to me, package was updated last time long time ago.  
I personally encountered 3 "bugs" because of package`s old state:
1. Not working `volume` block
Default config `/etc/i3blocks.conf` have this line: `/usr/share/i3blocks/$BLOCK_NAME`. So by default script is executed from this folder and have name of block.
Script with name `volume` has state from this [commit](https://github.com/vivien/i3blocks-contrib/commit/454581f5bc6ff2d882db78a5536612ecd19e7ed4#diff-99453a5b355c4b5041af99525b0594df). But current version from `i3blocks-contrib` is 6 commits ahead.  
Due to this volume blocket doesn`t work on my machine from the box: I get error like in issue #281 

2. Non standard variables are not supported
Current README FAQ states:
```
2. Can I use my own variables?
Yes, any variable defined in the block is exported as is to the environment of its command.
```
But current package does not support custom vars. e.g. if I define `qwe=1` in global area or in block, then run `i3blocks -c i3blocks.conf` from terminal, I get this:
```
ERROR parse_property:98: unknown key: "qwe"
ERROR main:70: Try 'i3blocks -h' for more information.
```
And bar show only error: `Error: status_command process exited unexpectedly`

Probably related to this #89.

3. Relative path for command is not working
Current README states for `command`  property:
```
command
... The command can be relative to the configuration file where it is defined.
```
  I tried to set command to relative bash script, but it did not work.

**Comment by vivien** [comment]
Scripts have been moved to the https://github.com/vivien/i3blocks-contrib repository. Please refer to it for problem 1.

For 2 and 3, the website reflect the current master of the README, not the 1.4 documentation.

I've just release an 1.5 version, you may expect a new package soon btw.

**Comment by jpleau** [comment]
Working on this, an update will be pushed to debian soon and I will upload updated versions for ubuntu xenial and bionic to my PPAs.

**Comment by WuerfelDev** [comment]
Hi @vivien the official ubuntu package is still version 1.4-4 
Can you update it? Thanks

**Comment by maxmalov** [comment]
Hi @jpleau, any updates on the new release?

**Comment by Joellidin** [comment]
I would love an update as well!

**Comment by mattiasflodin** [comment]
It's 2022 and Ubuntu still has i3blocks 1.4. Virtually none of the example configs and contrib scripts work with this version.
