### ISSUE TITLE
*/config vs */i3blocks.conf

### ISSUE THREAD

**Issue by hicksca** [vivien/i3blocks#386]
I may have another issue completely but have tested three different machines and this behavior seems consistent. 
It seems like I have to name my configuration file `i3blocks.conf` for i3blocks to find it. Even when I implicitly call it from i3 with ` status_command i3blocks -c $HOME/.config/i3blocks/config` . 
I'm fine doing this however in the documentation in the [README][1] reads as if you can name it this way:

> For the picky, you can start a configuration file in one of the following preferred paths:
> 
>     $XDG_CONFIG_HOME/i3blocks/config (or **~/.config/i3blocks/config**);
> 
>     ~/.i3blocks.conf;
> 
>     $XDG_CONFIG_DIRS/i3blocks/config (or /etc/xdg/i3blocks/config);
> 
>     /etc/i3blocks.conf;
> 
>     or any other path that you will specify using the -c option.

I did look through older issues to make sure this hadn't been answered already and this was the closest thing I found: /issues/234

[1]: https://github.com/vivien/i3blocks/blob/master/docs/README.adoc

**Comment by vivien** [comment]
Which version are you using?

**Comment by hicksca** [comment]
1.4
```
 ~ i3blocks -V
i3blocks 1.4 © 2014 Vivien Didelot and contributors
```

**Comment by vivien** [comment]
This must work as you expect with the master branch of this repository. Are you able to give it a try?

**Comment by hicksca** [comment]
Looks like I a permissions issue I didn't catch along the way.
Is working as expected.

![image](https://user-images.githubusercontent.com/3722310/62498100-17056c00-b7ac-11e9-8108-4ec0b3b2d6eb.png)

![image](https://user-images.githubusercontent.com/3722310/62498170-487e3780-b7ac-11e9-8533-cfe9ec238fe0.png)
