### ISSUE TITLE
i3blocks exited with status 0

### ISSUE THREAD

**Issue by sethpollen** [vivien/i3blocks#388]
First: Thanks for i3blocks! It is great.

Multiple times per day my i3blocks process exits, showing this message on the i3 bar:

Error: status_command process exited unexpectedly (exit 0)

I run i3blocks with -vv and collected its stderr after such a termination, but I don't see any explanation of why it died: https://github.com/sethpollen/sbp_linux_config/blob/master/i3blocks.stderr

Here is the config I use: https://github.com/sethpollen/sbp_linux_config/blob/master/common-text/dotfiles/config/i3blocks/config
And here is how I invoke i3blocks from i3: https://github.com/sethpollen/sbp_linux_config/blob/master/common-text/dotfiles/i3/config#L27

Any pointers for how to debug further?

**Comment by vivien** [comment]
Which i3blocks version are you using? Can you tell me if you're still encountering this with the latest master from this repository?

**Comment by sethpollen** [comment]
I was running i3blocks 1.4. I just installed from source and will let you know if the problem reoccurs. Thanks!

**Comment by zsugabubus** [comment]
"exited unexpectedly" means that the process terminated because of a signal, from "exit 0" I guess it received a `SIGKILL` most probably.

You should run something like `strace`, instead of dumping stderr to get more valuable info.

**Comment by sethpollen** [comment]
Sorry for the radio silence. I think I figured it out. I ran afoul of the warning at https://i3wm.org/docs/userguide.html#status_command about signal handling if you invoke i3blocks through a shell (fish in my case). I fixed the problem by 'exec'ing i3blocks from my fish command line instead of just calling it plainly. Thanks!

**Comment by vivien** [comment]
Good to know, I'm closing this!
