### ISSUE TITLE
Block position vs click position

### ISSUE THREAD

**Issue by guraltsev** [vivien/i3blocks#389]
This is more of a request than a bug. I am coding a small applet that gets launched when clicking on a block. I know I can get the coordinates of the click from the environment variables ``BLOCK_X`` and ``BLOCK_Y`` but I would actually want to display the applet in a fixed position over my block, not in a position that depends on the click location (the block has a large output so, at least horizontally, it can be a relevant distance).

Also, I am having a bit of difficulty interpreting this sentence from the documentation that says:

>Without lots of calculation to determine the block's location on the screen, this feature is only usable in personal scripts.

from [WritingYourOwnBlocklet](https://github.com/vivien/i3blocks/wiki/Writing-Your-Own-Blocklet). Does this reference this issue?

**Comment by guraltsev** [comment]
Looking at the i3bar documentation: can you introduce forwarding ``relative_x`` and ``relative_y`` as environment variables too?

**Comment by vivien** [comment]
> Looking at the i3bar documentation: can you introduce forwarding relative_x and relative_y as environment variables too?

With the latest master from this repository, you have access to these variables in your environment!
