### ISSUE TITLE
min_width and button events

### ISSUE THREAD

**Issue by jaboto** [vivien/i3blocks#390]
Hi,

I recently upgraded from Debian 9 to Debian 10 and detected a misbehavior that was not occurring before.

In an attempt to have a clock centered in the screen, I use a min_width parameter inside my block time2 which places correctly the time in the middle of the screen as shown below.
![image](https://user-images.githubusercontent.com/1579754/62468644-d64f2800-b796-11e9-879a-f7a3517391e5.png)

Also, the script pop-up a calendar in case of receiving the "Button 1" event as it can be seen in the simple script (I have removed the min_width in this case so it is not on the center).
![image](https://user-images.githubusercontent.com/1579754/62468798-33e37480-b797-11e9-8814-343148a4b15a.png)

So, this used to work well in Debian 9 but in Debian 10 the button is not registered. In fact I have been playing a bit with this and if the value is low (<100), the button event seems to be registered but not on the output itself but on the left part of the block (in red in the picture below):
![image](https://user-images.githubusercontent.com/1579754/62469046-b9ffbb00-b797-11e9-9582-e51e9e0e4a4e.png)

Anyone else experience the issue?
```
jaime@WeatherLight:~$ uname -a
Linux WeatherLight 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux
jaime@WeatherLight:~$ dpkg -l | grep i3blocks
ii  i3blocks                                  1.4-4                               amd64        highly flexible status line for the i3 window manager
```

**Comment by lasers** [comment]
You should try upgrading to current i3wm version and see if it's still happening. I don't think `i3blocks` is using `min_width` in their code at all other than to pass this and some other values to i3bar.

**Comment by vivien** [comment]
As @lasers said, that is unlikely related to i3blocks which is simply passing the `min_width` key to its parent process.
