### ISSUE TITLE
Color emoji not showing up on i3blocks

### ISSUE THREAD

**Issue by jtanadi** [vivien/i3blocks#392]
For some reason the emojis I'm using as labels are showing up as silhouettes.

Here's my config file (in the terminal):
![2019-08-06-18:36:35](https://user-images.githubusercontent.com/18740288/62591240-f79a3c00-b89c-11e9-8c5f-c93ef5fcb8b6.png)

And this is what the i3bar looks like:
![2019-08-06-18:36:13](https://user-images.githubusercontent.com/18740288/62591247-fbc65980-b89c-11e9-9888-c2cbdee48cc4.png)

I've been trying to find out why this is happening, but couldn't find an answer. Any pointer would be appreciated. Thanks!

**Comment by Pysis868** [comment]
What was the issue?  Mine just appear as error glyphs..
