### ISSUE TITLE
Labels no longer add a space before displaying command output

### ISSUE THREAD

**Issue by BrodieRobertson** [vivien/i3blocks#394]
Version: 1.5.2

Example Blocklet
[packages]
command=sudo pacman -Qu | wc -l
label=UPDATES
separator=true
interval=1800
signal=3

Output
![2019-09-08_17-01](https://user-images.githubusercontent.com/30792656/64485072-a34af900-d25a-11e9-8366-66642f47a6de.png)

Prior to the update the output would look like this:
![2019-09-08_17-11](https://user-images.githubusercontent.com/30792656/64485144-c88c3700-d25b-11e9-9cfd-06e2585f72c4.png)

**Comment by Nitroretro** [comment]
Same here, running on Arch. Got the update yesterday.

**Comment by BrodieRobertson** [comment]
I have a workaround for it in case it bothers you

command=echo "UPDATES $(sudo pacman -Qu | wc -l)"

**Comment by Nitroretro** [comment]
That works as well, although I just added an extra space after the `label` property which works just fine.

**Comment by vivien** [comment]
Hi @BrodieRobertson, note that this is a feature, not a bug. Some users did not want space between the label and the full_text, so the simplest was to remove it and let the users add one if they need one ;-)

I'll add a notice in the release note though.

**Comment by clink-aaron** [comment]
Trailing spaces in config files is never a good idea. To the point that most of us are using plugins to strip trailing spaces. 

If you insist on this weird convention, consider allowing something like:
```
label="TEMP "
```
and then stripping the quotes

**Comment by zsugabubus** [comment]
`label=` has been deprecated. And they are not add too much anyway, since you can as easily add a label as:

> command=echo "UPDATES $(sudo pacman -Qu | wc -l)"

…and it’s way more flexible.

**Comment by shivankgarg98** [comment]
Did anyone try using thinspace or half-space character instead of full-length space?
I try using this U+2009 but didn't get success.
I feel thinspace is just perfect - not too much space and not too compact.
Please let me know if you were able to make it work.
