### ISSUE TITLE
Set background color for disc, memory usage etc.

### ISSUE THREAD

**Issue by schlowm0** [vivien/i3blocks#401]
I know I can set the backgorund of any text, separator like this:
```
[separator1]
full_text=<span background="#0d64a5" foreground="#1f222d"> </span>
markup=pango
```
But what I don't know is how to change the background color of blocks like this one:
```
[memory]
color=#ff7400
label= 
command=/usr/share/i3blocks/memory
instance=swap
separator=false
interval=10
markup=pango
```

**Comment by zsugabubus** [comment]
Dunno, but have you tried setting `background=`?

**Comment by schlowm0** [comment]
Turns out my i3blocks was outdatet. After cloning the repo and reinstalling it, I could use the background property. The official ubuntu repo does not have the latest release
