### ISSUE TITLE
Cant get my external ip

### ISSUE THREAD

**Issue by DevJ4Y** [vivien/i3blocks#406]
I'm sorry if I'm just being stupid but i am new to most of this.

I have tried using multiple different one line commands inside the config file:
command=curl 'https://api.ipify.org/'
command=echo $(curl https://api.ipify.org)

i have tried making basic scripts 

#!/bin/bash

IP=$(wget http://ipinfo.io/ip -qO -)
echo -n $IP

all of which work when i run them outside of i3blocks and they also work for my mate using them inside i3 blocks

**Comment by gportay** [comment]
Try to remove the `-n` option from the command `echo`

Even better, just run the command `wget http://ipinfo.io/ip -qO-` directly in your script or

```
[ip]
command=wget http://ipinfo.io/ip -qO-
```

in your config file.

**Comment by usersina** [comment]
The key here is piping the result to xargs and echoing each line. Also add an interval just in case.

```bash
[ip]
command=wget http://ipinfo.io/ip -qO- | xargs echo
label=IP: 
interval=once
```

Check [this out](https://github.com/vivien/i3blocks#example) for more examples.

**Comment by vivien** [comment]
Indeed, https://api.ipify.org/ does not include a newline in its output, so you may force one with any of the two following commands:
```ini
command=echo $(curl -s https://api.ipify.org/)
command=curl -s https://api.ipify.org/ | xargs echo
```
You were close!
