### ISSUE TITLE
Passing environment variables or secrets to i3blocks

### ISSUE THREAD

**Issue by danihodovic** [vivien/i3blocks#407]
Is it possible to pass secret variables via the environment to i3blocks scripts? This is useful for API keys for example.

**Comment by gportay** [comment]
Have you tried that?

```
[hello]
myvar=world
command=echo Hello, $myvar!
interval=60
```
Maybe, it is what you want.

**Comment by danihodovic** [comment]
Any idea on how to get a variable into the i3 / i3blocks process?

**Comment by gportay** [comment]
It depends on how i3blocks is started. I guess you did not start i3blocks from a zsh instance. And thus, your blocklets will not have your variables set in the i3blocks environment.

I guess you have a display manager that starts your window manager (i3, sway or whatever) that starts i3blocks then from its config.

You have many way to solve your problem :) some are nice, some are uggly. I do not known enough on your setup to answer properly.

**Comment by gportay** [comment]
It is just a guess, I may be wrong.

**Comment by vivien** [comment]
As @gportay correctly stated, the environment variables from the process running i3 will be passed down to i3 and thus i3blocks. If i3 is run from your .zshrc file, make sure to `export MY_SECRET=foo` and `$MY_SECRET` will be available right away from within your block command.

I'm closing this issue, feel free to comment if you didn't solve this yet.
