### ISSUE TITLE
i3blocks not recognizing command

### ISSUE THREAD

**Issue by reikdas** [vivien/i3blocks#408]
Distro and DE - Manjaro i3 community edition

After a full system update, I could only see GPU USE, GPU TEMP(my own scripts) and the date in my i3 blocks and none of the rest.
I think this is because i3blocks was not recognizing i3blocks-contrib anymore.

I figured out a hacky solution - I took the relevant script out of their folders in i3blocks-contrib and it started working again. (`$SCRIPT_DIR` was correctly set to i3blocks-contrib location) But this did not work when I switched GPU to intel only - the GPU blocks still showed up taking space, just that they were empty since there was no GPU to detect. I guess this should not happen - it did not happen before, the blocks before that took up that space.

I decided to start from scratch. I purged i3blocks from my system. 
I installed i3blocks from pacman (as linked in the i3blocks README).
According to the instructions on the README (https://github.com/vivien/i3blocks#getting-started) -
I executed -
```
git clone https://github.com/vivien/i3blocks-contrib ~/.config/i3blocks
cd !$
cp config.example config
```
but I am only able to see the date and the time blocks on my i3blocks bar. (The same problem as before)

**Comment by gportay** [comment]
I guess it is because the `$SCRIPT_DIR` does not point to the location of the clone of i3blocks-contrib.

Try to set the command to `$HOME/.config/i3blocks/$BLOCK_NAME`

**Comment by reikdas** [comment]
Did not work. I still face the same issue as before of i3blocks-contrib scripts not being recognized.

**Comment by zsugabubus** [comment]
In `i3blocks-contrib` every script is in the same-named directory, so I guess you should try setting the default `command` like:
```cfg
command=$HOME/.config/i3blocks/$BLOCK_NAME/$BLOCK_NAME
```

**Comment by reikdas** [comment]
Thanks! That works. But this means that the sample script to get running does not work?

**Comment by zsugabubus** [comment]
Yeah, it very seems that it doesn't work out of box.

I think the intended usage of those blocklets is to copy the needed executables to a `$SCRIPT_DIR`, but... it's absolutely up to you how you make it work.

**Comment by reikdas** [comment]
> But this did not work when I switched GPU to intel only - the GPU blocks still showed up taking space, just that they were empty since there was no GPU to detect. I guess this should not happen - it did not happen before, the blocks before that took up that space.

I forgot to mention - the block labels for the non-custom script blocks didn't show up but the values did. 
Also, I still face this error :(

**Comment by zsugabubus** [comment]
- Do you have enough space on your screen?
- Try out just one blocklet at a time. Does it work?
- Share your config if you feel so.

**Comment by reikdas** [comment]
> Do you have enough space on your screen?

Yes

> Try out just one blocklet at a time. Does it work?

No :( 

This is how it looks when I have switched on my Nvidia GPU - 

![2019-11-09_09-40](https://user-images.githubusercontent.com/11775615/68522844-53c68f00-02d6-11ea-8478-9ae51ef62d18.png)

This is how it looks when I am running only on my Intel iGPU - 

![2019-11-09_09-49](https://user-images.githubusercontent.com/11775615/68522853-735db780-02d6-11ea-859f-7b9c4e56ccd4.png)

> Share your config if you feel so.

```
# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=$HOME/.config/i3blocks/$BLOCK_NAME/$BLOCK_NAME
separator_block_width=15
markup=none

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
label=MEM USE 
separator=false
interval=30

[memory]
label=SWAP 
instance=swap
separator=false
interval=30

# Network interface monitoring
#
# If the instance is not specified, use the interface used for default route.
# The address can be forced to IPv4 or IPv6 with -4 or -6 switches.
#[iface]
#IFACE=wlan0
#color=#00FF00
#interval=10
#separator=false

[wifi]
#INTERFACE=wlp3s0
label=wifi:
interval=10
separator=false

[bandwidth]
#INTERFACE=eth0
interval=5

# CPU usage
#
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[cpu_usage]
label=CPU USE 
interval=10
min_width=CPU 100.00%
#separator=false

# Generic media player support
#
# This displays "ARTIST - SONG" if a music is playing.
# Supported players are: spotify, vlc, audacious, xmms2, mplayer, and others.
#[mediaplayer]
#instance=spotify
#interval=5
#signal=10

# OpenVPN support
#
# Support multiple VPN, with colors.
#[openvpn]
#interval=20

# Temperature
#
# Support multiple chips, though lm-sensors.
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[temperature]
label=CPU TEMP 
interval=10

# Nvidia Usage
[nvidia use]
label=GPU USE 
command=/home/reik/.config/i3blocks/nvidia-use.sh
interval=1

# Nvidia Temperature
[nvidia]
label=GPU TEMP °C 
command=/home/reik/.config/i3blocks/nvidia.sh
#nvidia-settings -q gpucoretemp -t °C
#[load_average]
interval=1

# Key indicators
#
# Add the following bindings to i3 config file:
#
# bindsym --release Caps_Lock exec pkill -SIGRTMIN+11 i3blocks
# bindsym --release Num_Lock  exec pkill -SIGRTMIN+11 i3blocks
#[keyindicator]
#KEY=CAPS
#markup=pango
#interval=once
#signal=11

#[keyindicator]
#KEY=NUM
#markup=pango
#interval=once
#signal=11

# Battery indicator
#
# The battery instance defaults to 0.
[battery]
label=BAT 
#label=⚡
interval=10

# Date Time
#
[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1
```

**Comment by zsugabubus** [comment]
Does it persist if you restart i3 (`i3-msg restart`)? Do your GPU blocklets output something when you use Intel only?

I have no useful ideas but you could try [debugging i3blocks](https://github.com/vivien/i3blocks/#debugging) or run it in the terminal, maybe you can see something interesting.

**Comment by reikdas** [comment]
It seems like this was the offending block - 
```
#Nvidia Usage
[nvidia use]
label=GPU USE 
command=/home/reik/.config/i3blocks/nvidia-use.sh
interval=1
```

This is nvidia-use.sh - 
```
#!/bin/bash
nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu
```
Could any one throw any light on this?

**Comment by zsugabubus** [comment]
> > Do you have enough space on your screen?
>
> Yes

Eh... no.

> Do your GPU blocklets output something when you use Intel only?

The answer is **yes**. S*** `nvidia-smi` prints a long error message to stdout(!) and returns with an undocumented error code. To make things even worse, it prints an additional empty line after it.

So, `i3status` notices that your status line has grown too long and it tries shortening it (as it can be seen on your second screenshot). However, it also tries shortening the output of GPU usage because you provided a shorter variant, so it will expand to... nothing.

---

Didn't tested but try luck with this:

```cfg
[nvidia use]
label=GPU 
command=nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu -l 1
interval=persist
```

**Comment by reikdas** [comment]
> Didn't tested but try luck with this:
> 
> [nvidia use]
> label=GPU
> command=nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu -l 1
> interval=persist

That block doesn't show up :(

**Comment by zsugabubus** [comment]
Try running `nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu -l 1` in your terminal. It should display (only) one new line every second.

**Comment by reikdas** [comment]
It does. Not sure why the block doesn't show up :(

**Comment by vivien** [comment]
Hi @reikdas, you've dug a tricky situation. To keep it simple, the problem with nvidia-smi is that it flushes twice. So the first time i3blocks correctly reads the percentage, then the second time it reads no output and thus skips the block.

The quick fix to prevent the double flush is to pipe the output to our friendly cat:

```ini
[nvidia]
command=nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu -l 1 | cat
interval=persist
```

Now it raises a question to me whether i3blocks must clear a persistent block which flushes without data or not. Technically today i3blocks does the right thing, if the block has no default text and flushes its output without text, it's legit to assume that the block wants to display nothing.
