### ISSUE TITLE
Monospace spaces aren't mono spaces

### ISSUE THREAD

**Issue by XenGi** [vivien/i3blocks#413]
Ahoi,

I've configured i3 with:

`~/.config/i3/config`:
```
font pango:JetBrains Mono 8
bar {
    font pango:JetBrains Mono 8
    status_command i3blocks -c ~/.config/i3blocks/config
}
```

`~/.config/i3blocks/config`:
```
[cpu]
label=cpu:
interval=1
command=~/.config/i3blocks/graph.py cpu -p --length 8
markup=pango
```

This is how my script looks like:
```
$ ~/.config/i3blocks/graph.py cpu -p --length 8
[▒  ▃▆ ▄▃]  33%
[▒  ▃▆ ▄▃]  33%
#00ff00
```

The font really doesn't matter here. The problem is that the spaces in the 'graph' aren't the same size as the other chars, which should be the case with a monospace font. I also tried Dejavu Sans Mono with the same results. The rest of i3 looks ok. It's just the script output that doesn't work.

**Comment by zsugabubus** [comment]
i3blocks doesn't do any kind of drawing but if you really think it's an issue with it, it would more appropriate if you could post an image of the issue.

I tried and every character has the same width: `[▒12▃▆3▄▃]`. (Have you noticed that you have two spaces at the beginning?)

**Comment by XenGi** [comment]
![image](https://user-images.githubusercontent.com/1043980/73947048-2ac69200-48f7-11ea-8ace-5bf478376212.png)

Here you can see the spaces being smaller then other chars. Which indicates to me that the font used is not monospaced. Which means it doesn't use the configured font but falls back to a default one or smth.

**Comment by XenGi** [comment]
Just tried putting blocks and spaces in a i3block label. Same behaviour there. Everything except the spaces has the same with.

**Comment by zsugabubus** [comment]
>

**Comment by zsugabubus** [comment]
JetBrains Mono doesn't have that box drawing character glyphs so it falls back to a different font. Take a glimpse at your fontconfig. DejaVu Sans Mono has glyphs for them so it _should_ show them monospaced. Try change font size to 9-10 and check if there are any changes. These are my ideas.

**Comment by zsugabubus** [comment]
> Which indicates to me that the font used is not monospaced. Which means it doesn't use the configured font but falls back to a default one or smth.

DejaVu Sans Mono has these glyphs so it _should_ work with it. Sanity check: did you restarted i3 after changing font (or bar { font })? On the other hand JetBrains Mono doesn't have such glyphs so yes, in this case you should check your font configuration. Try `font pango:monospace 8`.

> I don't know exactly where the issue is. Atm I'm guessing it's i3blocks.

Surely not because i3blocks just produces text, that i3bar consumes then displays it.

> The font can't be the issue because in my terminal I use it too and there everything is correctly monospaced.

Depending on what terminal emulator you use, it's possible that it uses its own glyphs for some characters.

**Comment by XenGi** [comment]
You're right. I got it fixed now with dejavu. That was some interesting deep dive into i3bar and fonts. Thx for your help!
