### ISSUE TITLE
Cannot inject variables

### ISSUE THREAD

**Issue by davidfstein** [vivien/i3blocks#419]
I am trying to inject variables in my block to use in a script. Following the docs, I first tried this example
```
[counter]
_count=0
command=printf '{"full_text":"Counter: %s", "_count":%d}\n' $_count $((_count + 1))
format=json
interval=1
```
This fails. So I tried a simpler test
```
[test]
foo=bar
command=echo "$foo"
```
That also failed. The result of running ```i3blocks``` from the command line is
```
ERROR parse_property:98: unknown key: "foo"
ERROR main:70: Try 'i3blocks -h' for more information.
```
No matter what I try, using any non-defined keywords for variable injection breaks.

Im running Ubuntu 18.04 and have i3blocks 1.4.

**Comment by cgross95** [comment]
It looks like version 1.4 does not support dynamic properties. See #328.

If you don't feel like upgrading, as a little hack to get around it, you can also pass the variable in the command, like
```
[test]
command=foo=bar bash -c 'echo "$foo"'
interval=1
```

Or if you're using a script with no arguments or anything, you don't need to deal with the extra `bash -c`. For example, I was having this problem setting the step in the [volume](https://github.com/vivien/i3blocks-contrib/tree/master/volume) blocklet, so a config like
```
[volume]
command=STEP=1% $SCRIPT_DIR/volume
LABEL=VOL 
interval=once
signal=10
```
works just fine.
