### ISSUE TITLE
No spaces in some places

### ISSUE THREAD

**Issue by SodaLover** [vivien/i3blocks#428]
In my bar instead of
```
vol 85% | mem 1.7g/3.6g (47%) etc..
```
it does this:
```
vol85% | mem1.7g/3.6g (47%) etc..
```

**Comment by zsugabubus** [comment]
There is no space in the output because there is no space in your config. However, if you put space in your config…

**Comment by SodaLover** [comment]
How do i put spaces in my config? Where?

**Comment by zsugabubus** [comment]
`label=VOL` -> `label=VOL `.

Label is a text that is put before the output from the block.

**Comment by SodaLover** [comment]
Thank you once again!

**Comment by zsugabubus** [comment]
You’re welcome.

But next time please read through available documentation about `i3blocks`.
