### ISSUE TITLE
I3blocks is freezed while using any application in i3-gaps any workspace

### ISSUE THREAD

**Issue by bensh4** [vivien/i3blocks#431]
Using i3-gaps.When I launch a program, say SuperTuxKart (currently facing issues) after few seconds, I can see my i3blocks is freezed. Block buttons not working, time or nothing works at all. I need a refresh to get things working in i3blocks. After quitting program I saw blocks are back again. But, if I use workspace1 and 2 together with applications running, i3blocks is stuck again!

**Comment by zsugabubus** [comment]
> I need a refresh to get things working in i3blocks. After quitting program I saw blocks are back again.

Do you say you need to restart (refresh?) `i3blocks` to make it working again OR is it enough to quit from SuperTuxKart?

**Comment by bensh4** [comment]
> > I need a refresh to get things working in i3blocks. After quitting program I saw blocks are back again.
> 
> Do you say you need to restart (refresh?) `i3blocks` to make it working again OR is it enough to quit from SuperTuxKart?

Right now, when I quit SuperTuxKart, i3blocks is working without refresh. But, say not SuperTuxKart, I've also seen this issue while using Openshot editor at Workspace-1 and now it's freezed. Now I need refresh to start blocks to work again. But, in SuperTuxKart, after exists, blocks starts working.

**Comment by zsugabubus** [comment]
Hmm. Do you experience the issue with _only this_ in your `i3blocks/config`:
```
[clock]
command=date +%s
interval=1
```

If not: Hurray! Try finding out what block of yours causes it.

If does: Could you check whether this command `ps --no-heading -o state $(pgrep i3blocks)` returns “S”(leeping) or “R”(unning)? Maybe something stops i3blocks (in this case you will see “T”)? If you see “D”, then the best would be a `strace i3blocks` output to see what happens under the hood. I have no another idea.

**Comment by bensh4** [comment]
I just ran `ps --no-heading -o state $(pgrep i3blocks)` when i3blocks was stuck. It's returned "S"

**Comment by zsugabubus** [comment]
> So, it's killed when a program started?

i3blocks cannot respawn itself, it must be i3-gaps. But as far as I know, i3 only does this at startup + i3 restart, so for me it seems that your whole wm gets restarted for some reason. (If i3blocks would just simply die, you would see a “status_command exited unexpectedly” message in place of bar and i3 would not respawn it automatically.)

Try running `i3 -Vd all 2>>/tmp/i3err >>/tmp/i3log` and check logs, maybe you can find something interesting…

Also, if you do like this:
```cfg
# i3/config
bar {
	status_command	strace -Ao /tmp/strace i3blocks
}
```

You will see in “/tmp/strace” why/how was i3blocks terminated, search for “+++ (...reason...) +++”.

**Comment by zsugabubus** [comment]
This restart thing is interesting that I think is surely out of scope of `i3blocks`, and I do not see how it could be related to the fact that you see `i3blocks` frozen sometimes. They will be two separate issues, I guess. Anyway, have you experienced such freezes with:

```cfg
[clock]
command=date +%s
interval=1
```

At least that part could be fixed if not.

**Comment by bensh4** [comment]
Okay, I figured out the problem I hope. I set my i3blocks Block Button with dmenu. Basically, it's dmenu block button causes the problem. Set removed it and seems fixed. But, I can't guarantee feature issues. Anyways, thanks!
