### ISSUE TITLE
How to refresh i3blocks?

### ISSUE THREAD

**Issue by theonekeyg** [vivien/i3blocks#435]
Is there a way to refresh i3blocks from i3 config file?
For instance, with i3status you can send SIGUSR1 signal to i3status process to make it refresh, if there a way to do similar in i3blocks?

**Comment by zsugabubus** [comment]
Have you tried [this](https://github.com/vivien/i3blocks#signal)?

**Comment by theonekeyg** [comment]
whoops, somehow overlooked that, that works, thank you!
