### ISSUE TITLE
i3blocks freezes when switching wifi

### ISSUE THREAD

**Issue by HARSH-SHETH** [vivien/i3blocks#436]
**`I am facing a problem with 'i3blocks', When I connect to a new wifi network i3 freezes(accepts no input from keyboard) for 10-20 seconds. I looked into the i3blocks issues on github and did not find any similar problem. Is there any solution for this ?`**
Below is a screenshot of my config file - 
![This is my config file](https://user-images.githubusercontent.com/43717513/95672931-425ec480-0bc2-11eb-8165-c72d80d96b9e.jpeg)

**Comment by zsugabubus** [comment]
> i3 freezes … for 10-20 seconds. I looked into the i3blocks issues on github…

Have you considered looking around **i3** issues if you have issues with i3?

> Below is a screenshot of my config file

[Here is](https://www.youtube.com/watch?v=dQw4w9WgXcQ) a voice message of my comment.

> Is there any solution for this ?

Absolutely. At first round please try editing your comment if you need help because it is pretty useless in its current state.

**Comment by HARSH-SHETH** [comment]
Sorry for wasting your time, actually I didn't looked into i3 becuase problem started after I switched from i3status to i3blocks, I have looked into i3 issues now and found a similar issue there.

What additional info I should be stating when opening  a new issue?

**Comment by zsugabubus** [comment]
> Sorry for wasting your time

Do not say that. I commented because I would like to help, just the information you provided was very few and misleading. And that frustrated me. `i3blocks` has absolutely nothing to do with keyboard handling…

**Comment by HARSH-SHETH** [comment]
From next time I will try to provide more information. Thanks for replying.
