### ISSUE TITLE
A clock symbol after the bash script

### ISSUE THREAD

**Issue by Windslab** [vivien/i3blocks#437]
Do any bodey know how to fix my i3blocks? After run any script from a i3blocks i got a clock symbol!

My repo https://github.com/Windslab/ArchSpace

**Comment by zsugabubus** [comment]
I guess, it's because startup notifications. I see your whole `i3/config` is full of `--no-startup-id` (that's good), so probably using `command=i3-msg 'exec --no-startup-id' "urxvt -e $HOME/.config/foo"` fixes the issue. (Or something similar… you may need to play a little with escaping.)

**Comment by Windslab** [comment]
I did a lot of combinations and unfortunately it's doesn't work
