### ISSUE TITLE
Question: is it possible to control block intervals with environment variables?

### ISSUE THREAD

**Issue by andreesteve** [vivien/i3blocks#438]
Hi,

the scenario I have is that I use the same config for several machines. I would like to have different intervals on different machines (desktop vs laptop).

Is there a way to use environment variables; or any other mechanism to set the interval for blocks without having to have a separate config per machine?

Thank you!

**Comment by zsugabubus** [comment]
The short answer is no, because interval value is read as is, without substituting any environment variables. However you can tweak `command` a bit:
```
[block]
interval=persist
command=while date; do sleep $interval; done
```

**Comment by vivien** [comment]
Indeed as @zsugabubus correctly said, there is currently no way to control how i3blocks spawn block commands through the environment. But you can simply achieve this with a custom script for a persistent block:

```sh
#!/bin/sh

case $HOSTNAME in
  desktop) sleep=3 ;;
  laptop) sleep=5 ;;
  *) sleep=10 ;;
esac

while sleep $sleep ; do $some_commands ; done
```

Supporting default values from the environment like `interval=5 /usr/bin/i3blocks` is feasible but I'm worring that this would end up being confusing and erroneous.
