### ISSUE TITLE
Persistent command does not actually persist

### ISSUE THREAD

**Issue by swindlesmccoop** [vivien/i3blocks#461]
Command:
```
[audio]
command=pactl get-sink-volume alsa_output.pci`-0000_00_1b.0.analog-stereo | awk '{print $5}' | head -n 1
interval=persist
```
Result: It reads it properly on startup (ex output: 50%), but when adjusting, it doesn't change at all
Desired behavior: the percentage that the command is supposed to print out is printed every time it changes without using a `while true` loop since those end up using my CPU by and entire 3%, which there is no reason for it to do so.

**Comment by gportay** [comment]
First, the doc says

> The interval value persist (or -3) expects the command to be an infinite loop. Each line of the output will trigger an update of the block.

And your command is returning, I guess, because of piping commands.

I guess the purpose of `persist` is for blocklets that runs a command that never ends.

**Comment by gportay** [comment]
But I may be mistaken :)

**Comment by swindlesmccoop** [comment]
I guess I was just mistaken on what `persist` was for. Thanks.
