### ISSUE TITLE
timestamp reset on click

### ISSUE THREAD

**Issue by ghost** [vivien/i3blocks#64]
Hello!

I am using a script for an MPD-block, which uses the click functionality. Normally it shows the current song but when I right-click said block, it shows the progress of the current song (i.e. "3:49/5:06 (74%)") until the next time it is updated.
In its current form i3blocks shows the song progress for the remaining time, which could be any amount within the interval range. If the block's timestamp would be updated when clicked the delay would be persistent every time.
On the other hand, if the block's timestamp is updated and no update to its text is done, it could make the display inconsistent.

What do you prefer?

**Comment by Nycroth** [comment]
I think, if you feel the update timer for an interval should be reset on click, feel free to submit a patch for review. It makes no sense not to but nobody really had a reason to change it until you pointed it out.

**Comment by vivien** [comment]
I think the current behavior is the one people expect most.
