### ISSUE TITLE
Add more screenshots for prospective i3blocks users

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#68]
I think we should put up screenshots of different user configs so that prospective users of i3blocks can see it's potential. Here's mine (for now!):

![screenie](https://cloud.githubusercontent.com/assets/1966710/5152729/124c3d00-71c6-11e4-9330-e3a0cf4f6ab7.png)

It benefits potential users and also promotes collaboration amongst those of us who already use i3blocks.

**Comment by Zacorich** [comment]
![2015-03-14-174002_892x15_scrot](https://cloud.githubusercontent.com/assets/1131036/6652246/65f66b16-ca71-11e4-8c56-b0dd26fa56f1.png)
Very simple layout for for following
Sound Volume, Memory(RAM, SWAP, HDD), Network(Signal Force, Network Name, IP, Bandwidth), CPU(Usage, Temperature), Battery, Time(local, additional), Current Keyboard Layout, Applications With Tray icons if any(Skype for example)

Good luck with i3blocks!
