### ISSUE TITLE
Most plugins exiting  without (apparent) reason

### ISSUE THREAD

**Issue by lsmag** [vivien/i3blocks#69]
Hi,

I just replaced my i3status for i3blocks, and configured it to show only five blocks. Most of them - the battery and cpu blocks, for example, weren't showing anything, so I dig through the code and found two missing dependencies (acpi and mstat), but the blocks are still not working =S

This is the output:

```
$ i3blocks | grep bad
ERROR block_reap:239: [memory] bad exit code 127
ERROR block_reap:239: [battery] bad exit code 127
ERROR block_reap:239: [cpu] bad exit code 127
ERROR block_reap:239: [swap] bad exit code 127
```

The `.i3blocks.conf` I'm using is the same found in the repo, excluding a few blocks. I'm using Arch Linux, if it is somehow relevant.

So, what's going on? Is there an easy way to debug it to find the exact problem?

**Comment by lpasselin** [comment]
If you are seeing error 127 with python blocks only, make sure you downloaded the Block's requirements for your system's python environment. 

Using anaconda's python and running i3blocks from terminal will show the scripts working.  But text won't be shown on the bar.
