### ISSUE TITLE
Center a block on i3bar?

### ISSUE THREAD

**Issue by nim-** [vivien/i3blocks#70]
Would it be possible to make a block centered on i3bar?
I'm using xdotool on repeat to display window titles, which works flawlessly, except for the fact that I'd love to have this centered on the bar instead of aligned to the right.

Thanks for your time

**Comment by simonnagl** [comment]
Hi, just for information: I want to start developing the features discussed here. The discussion is at https://github.com/i3/i3/issues/1148.

**Comment by elhackerlibre** [comment]
Primero pido disculpa PorQue mi PREGUNTA esta muy fuera del tema!
@bchretien
 you use i3bar?
as you did to change the separator character ?
