### ISSUE TITLE
Better script for focused window

### ISSUE THREAD

**Issue by Airblader** [vivien/i3blocks#93]
This is just in the Wiki, but I think this script is superior and not much more complex:

````
command=xdotool getactivewindow getwindowname 2>/dev/null || echo "None"
```

It will work differently if no window is focused on the workspace. In this case, `xdotool` will error out. This causes the window title to not change, i.e., it will keep displaying the last focused window's title.

**Comment by vivien** [comment]
I updated the wiki with your suggestion. Feel free to do so ;-)
For this, it'd be great to have a Perl script to connect on the IPC socket and wait indefinitely for focus updates, in a blocklet with `interval=persist`. That way you can have instant update. The doc includes all needed Perl snippets: http://i3wm.org/docs/ipc.html#_subscribing_to_events
I'll try to find time for this, unless somebody is willing to write it.

**Comment by Airblader** [comment]
I wrote the following. I'm really sick today, though, so I'll stop right now and lay back down. It works if I execute it from the console, but somehow not via `command` and `interval=persist`. Not sure why. It's also missing handling for when the last container of a workspace was closed.

````
#!/usr/bin/env perl
use Data::Dumper;
use List::Util qw(first);
use AnyEvent;
use AnyEvent::I3;

use strict;
use warnings qw(FATAL utf8);
use v5.10;

my $i3 = i3();
$i3->connect->recv or die "failed to connect to i3";

$i3->subscribe({
  window => sub {
    my ($msg) = @_; 

    return unless $msg->{change} eq "focus" or $msg->{change} eq "title";
    say $msg->{container}->{name};
  }
})->recv->{success} or die "failed to subscribe to i3 events";

AE::cv->recv;
```

**Comment by rainerborene** [comment]
This might be related but the following blocklet does not work.
```
[focused window]
command=xtitle -s
interval=persist
```

**Comment by 8carlosf** [comment]
please check if you have the latest git version of i3blocks, it will not work with the last tagged version.
also check the command "xtitle -s" in your terminal, and see if it works okay (if not, install https://github.com/baskerville/xtitle or from the AUR if you are a archlinux user).
then it should all work.

**Comment by Airblader** [comment]
The xtitle solution is actually a whole lot better. And it works fine with persist mode for me.

**Comment by vivien** [comment]
I close this issue since the wiki is updated. The `xtitle` example is nice btw!

**Comment by fpcr** [comment]
That was AWESOME. the very last thing that bothered me with i3 is now gone!

**Comment by Alighorab** [comment]
```
[Title]
command=xdotool getactivewindow getwindowname 2> /dev/null || echo "None"
interval=1
```

I tried this and it worked just fine, way better than `xtitle`, I use `interval=1` 'cause `persist` does not work and `repeat` is killing the processor.

**Comment by nacht-falter** [comment]
Instead of using `interval=1` you could use a signal, so that the title is updated immediately when window focus changes:
```
[Title]
command=xdotool getactivewindow getwindowname 2> /dev/null || echo "None"
signal=1
```

Then add this to your i3 config file:

`exec_always --no-startup-id while :; do i3-msg -t subscribe '[ "window" ]' | grep -m 1 focus && pkill -SIGRTMIN+1 i3blocks; done`

Edit: fixed exec command
