### ISSUE TITLE
Make the header configurable

### ISSUE THREAD

**Issue by Airblader** [vivien/i3blocks#97]
Looking at https://github.com/i3/i3/issues/1598, the goal seems to be to move statusline related configuration into the JSON header.

With such a change, i3blocks should make an effort to make the contents of the header configurable.

**Comment by Airblader** [comment]
A first proposal:

````
[header]
click_events=true
```

Of course, this would break the config of users using a block named `header`. So this needs to be improved.

**Comment by Zopieux** [comment]
Maybe something a bit more verbose, such as

    [meta:header]

or even

    [i3blocks:header]

**Comment by vivien** [comment]
Just an idea, what about command line parameters to configure the header? That way we can assume good defaults, or have explicit config within the i3 config file.

**Comment by Airblader** [comment]
I like that. I'd hope the header doesn't get too complex anyway. I really think that i3bar should prefer moving into the direction of a separate config file if the i3 config isn't the right place anymore.

**Comment by vivien** [comment]
Me, I'm thinking about a way to set the `status_command` configuration within the i3 config file, and having a standard way for i3bar to pass it along to its `status_command`. I was imaginating something like this:

````
bar {
  position bottom
  workspace_buttons no
  tray_output none
  i3bar_command /mnt/data/src/i3/i3bar/i3bar
  status_command /mnt/data/src/i3blocks/i3blocks -vvv 2>/tmp/i3blocks.err
  status_config {
    command /usr/local/libexec/i3blocks/$BLOCK_NAME
    separator_block_width 15
    markup none
    block {
      name volume
      label VOL
      instance Master
      interval once
      signal 10
    }
    ...
    block {
      name date
      command date '+%Y-%m-%d %H:%M:%S'
      interval 5
    }
  }
  colors {
    separator  #005FD7
    statusline #FBFBFB
    background #000000
  }
}
````

That might be sent to the `status_command` on its stdin or something. Is it crazy?

**Comment by Airblader** [comment]
I guess this can be closed now since the corresponding issue has been closed.

**Comment by vivien** [comment]
Hi @Airblader, is a configurable header of some sort still relevant? I kinda lost track of this request. It looks like it isn't necessary anymore.

**Comment by Airblader** [comment]
No, this can remain closed.
