### ISSUE TITLE
Never again forget about your open mic!

### ISSUE THREAD

**Issue by msx** [vivien/i3blocks#98]
Hi all,
@Vivien, rest of the contributing folks: I just want to thank you'll for i3blocks, I just switched to it over last night and I love it.

So, here's my little contribution that I would like to add to the wiki in case anyone find it useful once we all agree it meets the minimum quality standards :)

---
# mic

I use Skype, Linphone and Hangouts every day at work and I constantly forget to mute the damn mic whenever I'm on a call but not participating on it actively or just waiting for my turn to speak.
I created this little block that hopefully will help me be aware whenever my mic is open so I can mute it and keep things professionally :D

Also I hope my pal @CaWa will stop babysitting me and telling me to shut the mic!

So without more ado here are some screenshots and the correspondent code.

## Screenshots

![2015-04-04_2620_1600x900]
(https://cloud.githubusercontent.com/assets/394089/6995501/be8ab838-db22-11e4-99f6-5909abca685b.png)
![2015-04-04_3033_1600x900](https://cloud.githubusercontent.com/assets/394089/6995542/3120dbaa-db25-11e4-9238-aaaca73c6a6c.png)
![micc_alt](https://cloud.githubusercontent.com/assets/394089/6995546/6bddf82c-db25-11e4-8081-96101f4a7921.png)
![mico](https://cloud.githubusercontent.com/assets/394089/6995547/6be11034-db25-11e4-9b59-bdfc06f1181f.png)
![mico_alt](https://cloud.githubusercontent.com/assets/394089/6995548/6be340e8-db25-11e4-9379-075b8aad51eb.png)
![micc](https://cloud.githubusercontent.com/assets/394089/6995549/6be567b0-db25-11e4-85be-3ccbd91b22ce.png)

As you can see on the above screenshots I already ship two variants of the mics shown - also the colors can be customized too.

**Fonts utilized:**
i3: _font pango:Terminus 9_  (frames, dialog boxes, status bar)
Eye candy: _Font Awesome_

## Code
Now the most important part is done (that is showing some fancy screenshots), here comes the code.
Relevant **~/.config/i3blocker/config** stuff:
```bash
...
command=~/.config/i3blocks/blocks/$BLOCK_NAME
[mic]
color=#FFFFFF
interval=5
...
```

**~/.config/i3blocker/blocks/mic**:
```bash
#!/bin/bash
# Copyright (C) 2015 Martín Cigorraga <archlinux.us: msx>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the Affero GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Check mouse event
case $BLOCK_BUTTON in
    3)
	#/usr/bin/amixer set Capture toggle &>/dev/null;  # AlsaMixer
	/usr/bin/pactl set-source-mute 1 toggle;  # PulseAudio
esac


# Determine mic's state
#amixer contents | grep -q "values=off" && [[ $? -eq 0 ]] && state="off";  # If you use AlaMixer
pactl list sources | grep -q "Mute: yes" && [[ $? -eq 0 ]] && state="off";  # If you rather go with PulseAudio


# Toggle mic's state
case $state in
    off)
	echo "  " " muted ";
	#echo "  "
	echo
	echo \#005FD7;  # Soft blue
	#echo \#00FF00;  # Bright green
	exit 0;
	;;
    *)
	echo "     " " OPEN   ";
	#echo "      ";
	exit 33;
	;;
esac

exit 0;
```

### Features
* Avoids possibly mistakes when you are unaware the mic is open :+1: 
* Lets you toggle MUTE state with a right-click.
* The script reads mic's state every 5 seconds (default) so if you set the mic state using AlsaMixer or similar app the change will be reflected on next refresh.
* I ship the script ready to use it with AlsaMixer and PulseAudio (default), you can toggle which backend you prefer by simply uncommenting the appropriate lines.
* If you happen to sometimes be faraway as I am, you will probably choose to use the bigger alert. However as everything is in plain text you can customize anything to your liking.

###### For toggling mic's state:
* _**amixer**_ (AlsaMixer)
* _**pactl**_ (PulseAudio)

###### Eye candy:
* _**Font Awesome**_, get it here: https://fortawesome.github.io/Font-Awesome/cheatsheet/
* _**Terminus**_ font (probably already shipped in your distro's repositories)

That's all for now, I hope **mic** will be useful for someone else.
_Any ideas/critics on how to improve this circus is welcome (in fact I would love to know about them)_.
Cheers!

**Comment by Zopieux** [comment]
I guess you can update the wiki *without* requesting it in an issue. Thanks for your work, seems really handy and pretty!

**Comment by msx** [comment]
Gonna move it then, thanks :)

**Comment by Nycroth** [comment]
Hope you don't mind, I just cleaned up the code a touch to keep a consistent style. I also removed the colour within the script because it should be set in the i3blocks config. A also fixed AlsaMixer's lines because the code didn't work for me when I used it.

Very clever idea btw! I'm very glad to have this going forward.

**Comment by msx** [comment]
Thank you *very* much, I will check everything later when I have a break.
Cheers!

**Comment by vivien** [comment]
Thanks @msx for this addition! I add the link here https://github.com/vivien/i3blocks/wiki/Blocklets#mic since it's definitely a good piece of work!

**Comment by msx** [comment]
Nice to see it could be useful to anyone else, thank you Vivien :)

**Comment by qazip** [comment]
Sorry, but is this script available in the contrib repo? I can't find it.
